# NanoBrain Test Result Constants Configuration
# ============================================
# 
# Framework-compliant configuration for standardized test result values
# following mandatory ConfigBase patterns and from_config loading.

# ✅ FRAMEWORK COMPLIANCE: All test result values configurable
success_value: "SUCCESS"
failure_value: "FAILURE"
pass_value: "PASS" 
fail_value: "FAIL"
pending_value: "PENDING"
skipped_value: "SKIPPED"
error_value: "ERROR"

description: "Default NanoBrain test result constants for framework compliance"

# ✅ CONFIGURATION METADATA
metadata:
  framework_version: "2.0.0"
  config_type: "test_constants"
  created_for: "test_framework_success_variable_fix"
  supports_customization: true
  
# ✅ USAGE EXAMPLES
examples:
  basic_usage: |
    from nanobrain.core.testing import SUCCESS, FAILURE, PASS, FAIL
    test_result = SUCCESS if condition else FAILURE
    
  enum_usage: |
    from nanobrain.core.testing import TestResult
    result = TestResult.SUCCESS
    
  config_loading: |
    from nanobrain.core.testing import TestConstants, TestResultConfig
    config = TestResultConfig.from_config("custom_test_constants.yml")
    constants = TestConstants.from_config(config) 