name: processing_step
description: Configuration for Step
debug_mode: true
_metadata:
  extracted_from: processing_step
  extraction_timestamp: '2025-06-22T23:24:34.921331'
  class_path: nanobrain.core.step.Step
