name: input_step
description: Configuration for Step
debug_mode: true
_metadata:
  extracted_from: input_step
  extraction_timestamp: '2025-06-22T23:24:34.920884'
  class_path: nanobrain.core.step.Step
