name: output_step
description: Configuration for Step
debug_mode: true
_metadata:
  extracted_from: output_step
  extraction_timestamp: '2025-06-22T23:24:34.921797'
  class_path: nanobrain.core.step.Step
