# Elasticsearch Genome Search Step Configuration
# nanobrain/library/workflows/chatbot_viral_integration/config/elasticsearch_genome_search.yml

# Step configuration
step_name: "elasticsearch_genome_search"
description: "High-performance virus genome search using Elasticsearch with Docker auto-installation"
timeout: 300  # 5 minutes for search operations
retry_attempts: 2

# Elasticsearch tool configuration
elasticsearch_config:
  # Connection settings
  host: "localhost"
  port: 9200
  scheme: "http"
  username: null
  password: null
  
  # Auto-installation settings
  auto_install_enabled: true
  container_name: "nanobrain-elasticsearch"
  image_name: "elasticsearch"
  image_tag: "8.14.0"
  
  # Resource limits for auto-installed container
  memory_limit: "2Gi"
  cpu_limit: "1.0"
  
  # Data persistence
  data_volume_name: "nanobrain-elasticsearch-data"
  backup_enabled: true
  
  # Network configuration
  network_name: "nanobrain-network"
  
  # Health monitoring
  health_check_enabled: true
  health_check_interval: 30
  
  # Index configuration
  default_index: "nanobrain-search"
  virus_genome_index: "virus-genomes"

# Search configuration
confidence_threshold: 0.7
max_results: 20
enable_fuzzy_search: true
fallback_to_csv: true

# CSV fallback configuration (for compatibility)
csv_file_path: "data/BVBRC_genome_alphavirus.csv"

# Performance settings
search_timeout: 30
cache_results: true
cache_ttl: 3600  # 1 hour

# NanoBrain framework integration
parallel_execution: false
resource_requirements:
  memory: "512Mi"
  cpu: "0.5"

# Step dependencies
dependencies: []

# Output configuration
outputs:
  - name: "genome_matches"
    type: "list"
    description: "List of matching virus genomes"
  - name: "search_metadata"
    type: "dict"
    description: "Search execution metadata"

# Metadata
metadata:
  category: "search"
  tags: ["elasticsearch", "virus", "genome", "search"]
  version: "1.0.0"
  author: "NanoBrain Framework"
  created: "2025-06-26"
  updated: "2025-06-26" 