name: AlphavirusWorkflow
description: Comprehensive 14-step Alphavirus protein analysis workflow
version: 4.2.0
execution_strategy: sequential
error_handling: continue
enable_monitoring: true
workflow_directory: nanobrain/library/workflows/viral_protein_analysis
enable_progress_reporting: true
progress_batch_interval: 3.0
progress_collapsed_by_default: true
progress_show_technical_errors: true
progress_preserve_session_history: true
max_parallel_steps: 2
step_timeout: 1800.0
retry_attempts: 2
retry_delay: 5.0
validate_graph: true
allow_cycles: false
require_connected_graph: true
steps:
- step_id: data_acquisition
  name: BV-BRC Data Acquisition
  description: Acquire and filter alphavirus genome data from BV-BRC database
  class: nanobrain.library.workflows.viral_protein_analysis.steps.bv_brc_data_acquisition_step.BVBRCDataAcquisitionStep
  estimated_time: 120.0
  config_file: config/steps/data_acquisition.yml
- step_id: genome_filtering
  name: Genome Quality Filtering
  description: Apply quality filters to acquired genome data
  class: GenomeFilteringStep
  estimated_time: 30.0
  config_file: config/steps/genome_filtering.yml
- step_id: protein_extraction
  name: Protein Sequence Extraction
  description: Extract protein sequences from filtered genomes
  class: ProteinExtractionStep
  estimated_time: 60.0
  config_file: config/steps/protein_extraction.yml
- step_id: sequence_annotation
  name: Sequence Annotation Enhancement
  description: Enhance protein annotations with functional information
  class: SequenceAnnotationStep
  estimated_time: 90.0
  config_file: config/steps/sequence_annotation.yml
- step_id: annotation_standardization
  name: Annotation Standardization
  description: Standardize protein annotations across genomes
  class: AnnotationStandardizationStep
  estimated_time: 45.0
  config_file: config/steps/annotation_standardization.yml
- step_id: genome_schematic
  name: Genome Organization Analysis
  description: Analyze and visualize alphavirus genome organization
  class: GenomeSchematicStep
  estimated_time: 30.0
  config_file: config/steps/genome_schematic.yml
- step_id: length_analysis
  name: Sequence Length Analysis
  description: Analyze protein sequence length distributions
  class: LengthAnalysisStep
  estimated_time: 20.0
  config_file: config/steps/length_analysis.yml
- step_id: sequence_curation
  name: Sequence Curation
  description: Curate sequences based on quality metrics
  class: nanobrain.library.workflows.viral_protein_analysis.steps.sequence_curation_step.SequenceCurationStep
  estimated_time: 60.0
  config_file: config/steps/sequence_curation.yml
- step_id: clustering_analysis
  name: Protein Clustering Analysis
  description: Cluster proteins by sequence similarity
  class: nanobrain.library.workflows.viral_protein_analysis.steps.clustering_step.ClusteringStep
  estimated_time: 180.0
  config_file: config/steps/clustering_analysis.yml
- step_id: multiple_alignment
  name: Multiple Sequence Alignment
  description: Create multiple sequence alignments for each cluster
  class: AlignmentStep
  estimated_time: 240.0
  config_file: config/steps/multiple_alignment.yml
- step_id: pssm_generation
  name: PSSM Matrix Generation
  description: Generate Position-Specific Scoring Matrices
  class: PSSMGenerationStep
  estimated_time: 120.0
  config_file: config/steps/pssm_generation.yml
- step_id: conservation_analysis
  name: Conservation Pattern Analysis
  description: Analyze conservation patterns across alignments
  class: ConservationAnalysisStep
  estimated_time: 90.0
  config_file: config/steps/conservation_analysis.yml
- step_id: quality_assessment
  name: Final Quality Assessment
  description: Comprehensive quality assessment of results
  class: QualityAssessmentStep
  estimated_time: 60.0
  config_file: config/steps/quality_assessment.yml
- step_id: report_generation
  name: Comprehensive Report Generation
  description: Generate final analysis report with all results
  class: nanobrain.library.workflows.viral_protein_analysis.steps.report_generation_step.ReportGenerationStep
  estimated_time: 45.0
  config_file: config/steps/report_generation.yml
links:
- link_id: acquisition_to_filtering
  source: data_acquisition
  target: genome_filtering
  link_type: direct
  data_mapping:
    genomes: original_genomes
    metadata: acquisition_metadata
- link_id: filtering_to_extraction
  source: genome_filtering
  target: protein_extraction
  link_type: direct
  data_mapping:
    filtered_genomes: filtered_genomes
    quality_report: filtering_report
- link_id: extraction_to_annotation
  source: protein_extraction
  target: sequence_annotation
  link_type: direct
  data_mapping:
    protein_sequences: protein_sequences
    extraction_metadata: extraction_metadata
- link_id: annotation_to_standardization
  source: sequence_annotation
  target: annotation_standardization
  link_type: direct
  data_mapping:
    annotated_sequences: annotated_sequences
    annotation_data: annotation_data
- link_id: standardization_to_schematic
  source: annotation_standardization
  target: genome_schematic
  link_type: direct
  data_mapping:
    standardized_annotations: standardized_annotations
    genome_data: genome_data
- link_id: schematic_to_length
  source: genome_schematic
  target: length_analysis
  link_type: direct
  data_mapping:
    protein_data: protein_data
    genome_organization: genome_organization
- link_id: length_to_curation
  source: length_analysis
  target: sequence_curation
  link_type: direct
  data_mapping:
    length_analysis: length_analysis
    sequences: sequences
- link_id: curation_to_clustering
  source: sequence_curation
  target: clustering_analysis
  link_type: direct
  data_mapping:
    curated_sequences: curated_sequences
    curation_report: curation_report
- link_id: clustering_to_alignment
  source: clustering_analysis
  target: multiple_alignment
  link_type: direct
  data_mapping:
    clusters: clusters
    cluster_representatives: cluster_representatives
- link_id: alignment_to_pssm
  source: multiple_alignment
  target: pssm_generation
  link_type: direct
  data_mapping:
    alignments: alignments
    alignment_quality: alignment_quality
- link_id: pssm_to_conservation
  source: pssm_generation
  target: conservation_analysis
  link_type: direct
  data_mapping:
    pssm_matrices: pssm_matrices
    alignments: alignments
- link_id: conservation_to_qa
  source: conservation_analysis
  target: quality_assessment
  link_type: direct
  data_mapping:
    conservation_data: conservation_data
    analysis_results: analysis_results
- link_id: qa_to_report
  source: quality_assessment
  target: report_generation
  link_type: direct
  data_mapping:
    quality_metrics: quality_metrics
    all_results: workflow_results
data_units:
- name: GenomeData
  type: genomic_sequences
  persistence: persistent
- name: ProteinData
  type: protein_sequences
  persistence: persistent
- name: AnnotationData
  type: functional_annotations
  persistence: persistent
- name: ClusterData
  type: sequence_clusters
  persistence: persistent
- name: AlignmentData
  type: multiple_alignments
  persistence: persistent
- name: PSSMData
  type: scoring_matrices
  persistence: persistent
monitoring:
  enabled: true
  metrics:
  - step_execution_time
  - data_quality_scores
  - sequence_count_tracking
  - memory_usage
  - disk_usage
  alerts:
  - condition: step_execution_time > 1800
    action: log_warning
  - condition: memory_usage > 8GB
    action: notify_admin
  - condition: sequence_count < 100
    action: quality_warning
quality_checks:
- step: data_acquisition
  checks:
  - genome_count >= 50
  - api_response_time < 30
- step: clustering_analysis
  checks:
  - cluster_count >= 5
  - largest_cluster_size < 500
- step: multiple_alignment
  checks:
  - alignment_quality_score > 0.7
  - gap_percentage < 50
resources:
  memory_limit: 16GB
  disk_space_limit: 100GB
  cpu_cores: 4
  temporary_directory: /tmp/alphavirus_workflow
  cleanup_intermediate_files: true
  keep_final_results: true
  retention_days: 30
testing:
  mock_backend_responses: false
  use_real_data: true
  test_datasets:
  - small_alphavirus_set
  - representative_genomes
  - quality_control_set
  validation_tests:
  - end_to_end_execution
  - data_integrity_checks
  - performance_benchmarks
_metadata:
  last_updated: '2025-06-22T23:41:37.451641'
  updated_by: modular_config_migration
  migration_version: 1.0.0
  uses_modular_config: true
