name: AlphavirusWorkflow
description: Comprehensive Alphavirus protein analysis workflow with implemented steps only
version: 4.5.0
execution_strategy: sequential
error_handling: continue
enable_monitoring: true
workflow_directory: nanobrain/library/workflows/viral_protein_analysis
enable_progress_reporting: true
progress_batch_interval: 3.0
progress_collapsed_by_default: true
progress_show_technical_errors: true
progress_preserve_session_history: true
max_parallel_steps: 2
step_timeout: 1800.0
retry_attempts: 2
retry_delay: 5.0
validate_graph: true
allow_cycles: false
require_connected_graph: true

# Tool dependencies configuration (Phase 3 compliance)
tools:
  bv_brc_tool:
    config_file: config/tools/bv_brc_tool.yml
    description: BV-BRC data acquisition tool configured for Alphavirus analysis
    required_for_steps: [data_acquisition]
    version: "2.0.0"
    compliance_status: "from_config_compliant"
  mmseqs2_tool:
    config_file: config/tools/mmseqs2_tool.yml
    description: MMseqs2 clustering tool optimized for viral protein analysis
    required_for_steps: [clustering_analysis]
    version: "2.0.0"
    compliance_status: "from_config_compliant"
  muscle_tool:
    config_file: config/tools/muscle_tool.yml
    description: MUSCLE alignment tool configured for viral protein sequences
    required_for_steps: [multiple_alignment]
    version: "2.0.0"
    compliance_status: "from_config_compliant"

steps:
- step_id: data_acquisition
  name: BV-BRC Data Acquisition
  description: Acquire and filter alphavirus genome data from BV-BRC database
  class: nanobrain.library.workflows.viral_protein_analysis.steps.bv_brc_data_acquisition_step.BVBRCDataAcquisitionStep
  estimated_time: 120.0
  config_file: config/steps/data_acquisition_config.yml
  dependencies:
    tools: [bv_brc_tool]
- step_id: annotation_mapping
  name: Annotation Mapping
  description: Map and standardize protein annotations
  class: nanobrain.library.workflows.viral_protein_analysis.steps.annotation_mapping_step.AnnotationMappingStep
  estimated_time: 60.0
  config_file: config/steps/annotation_mapping_config.yml
- step_id: sequence_curation
  name: Sequence Curation
  description: Curate sequences based on quality metrics
  class: nanobrain.library.workflows.viral_protein_analysis.steps.sequence_curation_step.SequenceCurationStep
  estimated_time: 60.0
  config_file: config/steps/sequence_curation_config.yml
- step_id: clustering_analysis
  name: Protein Clustering Analysis
  description: Cluster proteins by sequence similarity
  class: nanobrain.library.workflows.viral_protein_analysis.steps.clustering_step.ClusteringStep
  estimated_time: 180.0
  config_file: config/steps/clustering_config.yml
  dependencies:
    tools: [mmseqs2_tool]
- step_id: multiple_alignment
  name: Multiple Sequence Alignment
  description: Create multiple sequence alignments for each cluster
  class: nanobrain.library.workflows.viral_protein_analysis.steps.alignment_step.AlignmentStep
  estimated_time: 240.0
  config_file: config/steps/alignment_config.yml
  dependencies:
    tools: [muscle_tool]
- step_id: pssm_analysis
  name: PSSM Analysis
  description: Generate Position-Specific Scoring Matrices
  class: nanobrain.library.workflows.viral_protein_analysis.steps.pssm_analysis_step.PSSMAnalysisStep
  estimated_time: 120.0
  config_file: config/steps/pssm_analysis_config.yml

links:
- link_id: acquisition_to_annotation
  source: data_acquisition
  target: annotation_mapping
  link_type: direct
  data_mapping:
    protein_annotations: protein_annotations
    unique_proteins: unique_proteins
- link_id: annotation_to_curation
  source: annotation_mapping
  target: sequence_curation
  link_type: direct
  data_mapping:
    standardized_annotations: annotations
- link_id: curation_to_clustering
  source: sequence_curation
  target: clustering_analysis
  link_type: direct
  data_mapping:
    curated_sequences: sequences
- link_id: clustering_to_alignment
  source: clustering_analysis
  target: multiple_alignment
  link_type: direct
  data_mapping:
    clusters: clusters
    cluster_representatives: cluster_representatives
- link_id: alignment_to_pssm
  source: multiple_alignment
  target: pssm_analysis
  link_type: direct
  data_mapping:
    aligned_clusters: aligned_clusters
    alignments: alignments

data_units:
- name: GenomeData
  type: genomic_sequences
  persistence: persistent
- name: ProteinData
  type: protein_sequences
  persistence: persistent
- name: AnnotationData
  type: functional_annotations
  persistence: persistent
- name: ClusterData
  type: sequence_clusters
  persistence: persistent
- name: AlignmentData
  type: sequence_alignments
  persistence: persistent
- name: PSSMData
  type: pssm_matrices
  persistence: persistent

# Workflow metadata
workflow_metadata:
  framework_compliance: "from_config_mandatory"
  migration_status: "phase3_complete"
  cleanup_status: "unused_configs_removed_v4.5.0"
  last_updated: "2025-01-28"
  implemented_steps_only: true
  configuration_status: "production_ready"
