name: AlphavirusWorkflow
description: Comprehensive viral protein analysis workflow with enhanced ultra-precision data acquisition
version: 5.0.0
execution_strategy: event_driven  # CRITICAL: Event-driven strategy
error_handling: continue
enable_monitoring: true
workflow_directory: nanobrain/library/workflows/viral_protein_analysis
enable_progress_reporting: true
progress_batch_interval: 3.0
progress_collapsed_by_default: true
progress_show_technical_errors: true
progress_preserve_session_history: true
max_parallel_steps: 2
step_timeout: 30.0
retry_attempts: 2
retry_delay: 5.0
validate_graph: true
allow_cycles: false
require_connected_graph: true

# Data directory configuration - configurable paths for data storage and caching
data_directory: "data"  # Base data directory - can be overridden by environment or config
bvbrc_cache_directory: "data/bvbrc_cache"  # BV-BRC specific cache directory
mmseqs2_cache_directory: "data/mmseqs2_cache"  # MMseqs2 cache directory
cache_directory: "data/cache"  # General cache directory
csv_file_path: "data/viral_analysis/BVBRC_genome_viral.csv"  # Path to genome CSV data

# MIGRATED WORKFLOW CONFIGURATION: References to step-specific config directories
steps:
  - step_id: data_acquisition
    config_file: config/DataAcquisitionStep/DataAcquisitionStep.yml
  - step_id: annotation_mapping
    config_file: config/steps/annotation_mapping_config.yml
  - step_id: sequence_curation
    config_file: config/steps/sequence_curation_config.yml
  - step_id: clustering_analysis
    config_file: config/ClusteringStep/ClusteringStep.yml

# EVENT-DRIVEN LINKS: Define data flow between step data units
links:
  - link_id: workflow_to_acquisition
    source: workflow_input
    target: data_acquisition.synonyms_input
    description: "Route enhanced virus resolution output to enhanced data acquisition"
    
  - link_id: acquisition_to_annotation
    source: data_acquisition.validated_genomes
    target: annotation_mapping.fasta_and_annotations
    description: "Route validated genomes to annotation mapping"
    
  - link_id: annotation_to_curation
    source: annotation_mapping.standardized_annotations
    target: sequence_curation.standardized_annotations
    description: "Route standardized annotations to sequence curation"
    
  - link_id: curation_to_clustering
    source: sequence_curation.curated_sequences
    target: clustering_analysis.curated_sequences
    description: "Route curated sequences to clustering analysis"
    
  - link_id: clustering_to_workflow
    source: clustering_analysis.sequence_clusters
    target: workflow_output
    description: "Route clustering results to workflow output"

# MINIMAL WORKFLOW DATA UNITS: Only input/output for workflow-as-step usage
input_data_units:
  workflow_input:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: workflow_input
    description: "Enhanced workflow input with ultra-high-confidence synonyms and validation criteria"
    persistent: false

output_data_units:
  workflow_output:
    class: nanobrain.core.data_unit.DataUnitFile
    name: workflow_output
    description: "Complete workflow results with enhanced precision validation"
    persistent: true
    file_path: "results/enhanced_viral_protein_analysis.json"

# NO STEP-LEVEL DATA UNITS: All data units defined at step level
# NO WORKFLOW-LEVEL TRIGGERS: All triggers defined at step level
# NO TOOL CONFIGURATIONS: All tools configured at step level

# Workflow metadata
workflow_metadata:
  framework_compliance: "event_driven_architecture"
  migration_status: "enhanced_precision_complete"
  last_updated: "2025-01-28"
  configuration_status: "ultra_precision_event_driven"
  enhanced_features: "ultra_high_confidence_validation_pipeline"
  notes: "Updated for enhanced ultra-precision data acquisition with zero contamination tolerance"
