tool_name: bv_brc
tool_card:
  name: bv_brc
  description: BV-BRC tool for bacterial and viral genome analysis
  version: 1.0.0
  category: bioinformatics
  capabilities:
    - genome_analysis
    - protein_extraction
    - viral_data

# Installation configuration
installation_path: /Applications/BV-BRC.app
executable_path: /Applications/BV-BRC.app/deployment/bin
conda_channel: conda-forge
local_installation_paths:
  - /Applications/BV-BRC.app/deployment/bin
  - /Applications/BV-BRC.app/Contents/Resources/deployment/bin

# BV-BRC specific setting
genome_batch_size: 50
md5_batch_size: 25
min_genome_length: 8000
max_genome_length: 15000
use_cache: true
verify_on_init: false

# Progressive scaling configuration
progressive_scaling:
  1:
    limit: 5
    batch_size: 5
    description: "Small test"
  2:
    limit: 10
    batch_size: 10
    description: "Basic validation"
  3:
    limit: 20
    batch_size: 15
    description: "Medium test"
  4:
    limit: 50
    batch_size: 25
    description: "Full scale"

initial_scale_level: 1
detailed_diagnostics: true
suggest_fixes: true 