name: CleanAlphavirusWorkflow
description: Clean Alphavirus protein analysis workflow with external config references
version: 2.1.0
execution_strategy: sequential
error_handling: stop
input_parameters:
  target_genus:
    type: string
    default: Alphavirus
    description: Target genus for analysis
  custom_virus_name:
    type: string
    default: null
    description: Specific virus name for targeted analysis
  min_genome_length:
    type: integer
    default: 8000
    description: Minimum genome length filter
  max_genome_length:
    type: integer
    default: 15000
    description: Maximum genome length filter
steps:
- step_id: data_acquisition
  config_file: steps/data_acquisition_config.yml
- step_id: annotation_mapping
  config_file: steps/annotation_mapping_config.yml
- step_id: sequence_curation
  config_file: steps/sequence_curation_config.yml
- step_id: clustering
  config_file: steps/clustering_config.yml
- step_id: alignment
  config_file: steps/alignment_config.yml
- step_id: pssm_analysis
  config_file: steps/pssm_analysis_config.yml
workflow_directory: nanobrain/library/workflows/viral_protein_analysis/config
workflow_config:
  enable_caching: true
  cache_directory: cache
  output_directory: output
  log_level: INFO
  max_parallel_steps: 1
_metadata:
  last_updated: '2025-06-22T23:41:37.458965'
  updated_by: modular_config_migration
  migration_version: 1.0.0
  uses_modular_config: true
