# Enhanced Email Configuration for Viral Protein Analysis
# Phase 3 Implementation - Email Manager with Optional Usage

email_config:
  default_email: "onarykov@anl.gov"
  
  # Service-specific email usage
  service_usage:
    bvbrc_api:
      required: false
      use_email: false  # Anonymous access
      fallback_with_auth: true
      description: "BV-BRC API access (anonymous by default)"
      
    pubmed_api:
      required: true   # For rate limiting
      use_email: true
      respect_rate_limits: true
      description: "PubMed API access (email required for rate limiting)"
      
    ncbi_entrez:
      required: true
      use_email: true
      respect_rate_limits: true
      description: "NCBI Entrez utilities"
      
  # Rate limiting configuration
  rate_limiting:
    pubmed:
      max_requests_per_hour: 100
      aggressive_caching: true
      cache_duration_hours: 168  # 1 week
      backoff_strategy: "exponential"
      
    bvbrc:
      max_requests_per_second: 10
      anonymous_limits: true
      batch_size: 50
      retry_attempts: 3
      
    ncbi_entrez:
      max_requests_per_second: 3  # NCBI recommendation
      respect_weekends: true
      max_requests_per_minute: 10
      
  # Environment-specific configuration
  environments:
    testing:
      timeout_seconds: 10
      use_cached_responses: true
      mock_api_calls: true
      reduced_rate_limits: true
      
    production:
      timeout_hours: 48
      use_cached_responses: true
      mock_api_calls: false
      full_rate_limits: true
      
    development:
      timeout_seconds: 30
      use_cached_responses: true
      mock_api_calls: false
      debug_logging: true

  # EEEV-specific configuration
  eeev_specific:
    literature_search_terms:
      - "Eastern equine encephalitis virus"
      - "EEEV"
      - "alphavirus"
    
    priority_proteins:
      - "capsid protein"
      - "envelope protein E1"
      - "envelope protein E2"
      - "6K protein"
      
    expected_genome_size:
      min_kb: 10.5
      max_kb: 12.5
      typical_kb: 11.7 