email_config:
  default_email: onarykov@anl.gov
  service_usage:
    bvbrc_api:
      required: false
      use_email: false
      fallback_with_auth: true
      description: BV-BRC API access (anonymous by default)
    pubmed_api:
      required: true
      use_email: true
      respect_rate_limits: true
      description: PubMed API access (email required for rate limiting)
    ncbi_entrez:
      required: true
      use_email: true
      respect_rate_limits: true
      description: NCBI Entrez utilities
  rate_limiting:
    pubmed:
      max_requests_per_hour: 100
      aggressive_caching: true
      cache_duration_hours: 168
      backoff_strategy: exponential
    bvbrc:
      max_requests_per_second: 10
      anonymous_limits: true
      batch_size: 50
      retry_attempts: 3
    ncbi_entrez:
      max_requests_per_second: 3
      respect_weekends: true
      max_requests_per_minute: 10
  environments:
    testing:
      timeout_seconds: 10
      use_cached_responses: true
      mock_api_calls: true
      reduced_rate_limits: true
    production:
      timeout_hours: 48
      use_cached_responses: true
      mock_api_calls: false
      full_rate_limits: true
    development:
      timeout_seconds: 30
      use_cached_responses: true
      mock_api_calls: false
      debug_logging: true
  eeev_specific:
    literature_search_terms:
    - Eastern equine encephalitis virus
    - EEEV
    - alphavirus
    priority_proteins:
    - capsid protein
    - envelope protein E1
    - envelope protein E2
    - 6K protein
    expected_genome_size:
      min_kb: 10.5
      max_kb: 12.5
      typical_kb: 11.7
_metadata:
  last_updated: '2025-06-22T23:41:37.554699'
  updated_by: modular_config_migration
  migration_version: 1.0.0
  uses_modular_config: true
