tool:
  name: muscle
  installation_path: null
  executable_path: null
alignment:
  max_iterations: 16
  diagonal_optimization: true
  gap_open_penalty: -12.0
  gap_extend_penalty: -1.0
  output_format: fasta
quality:
  min_sequences: 3
  max_sequences: 1000
  min_conservation_threshold: 0.5
  max_gap_percentage: 50
conservation:
  calculate_profile: true
  highly_conserved_threshold: 0.8
  position_scoring: true
quality_scoring:
  enabled: true
  weights:
    conservation_score: 0.5
    gap_penalty: 0.3
    size_bonus: 0.2
  thresholds:
    high_quality_threshold: 0.7
    acceptable_quality_threshold: 0.5
performance:
  parallel_processing: false
  memory_optimization: true
output:
  export_conservation_profile: true
  export_quality_metrics: true
  keep_intermediate_files: false
  available_formats:
  - fasta
  - clustal
  - phylip
error_handling:
  retry_failed_alignments: true
  max_retry_attempts: 2
  skip_problematic_clusters: true
logging:
  log_level: INFO
  log_alignment_progress: true
  log_quality_metrics: true
  log_conservation_analysis: true
  detailed_statistics: true
_metadata:
  last_updated: '2025-06-22T23:41:37.608564'
  updated_by: modular_config_migration
  migration_version: 1.0.0
  uses_modular_config: true
