tool:
  name: pssm_generator
pssm_parameters:
  pseudocount: 0.01
  amino_acid_alphabet: ACDEFGHIKLMNPQRSTVWY
  log_odds: true
  normalize: true
background_frequencies:
  A: 0.0825
  C: 0.0137
  D: 0.0546
  E: 0.0675
  F: 0.0386
  G: 0.0708
  H: 0.0227
  I: 0.0596
  K: 0.0584
  L: 0.0966
  M: 0.0242
  N: 0.0406
  P: 0.047
  Q: 0.0393
  R: 0.0553
  S: 0.0656
  T: 0.0534
  V: 0.0687
  W: 0.0108
  Y: 0.0292
quality_thresholds:
  min_sequences: 3
  min_conservation: 0.5
  gap_threshold: 0.5
validation:
  check_matrix_completeness: true
  validate_score_ranges: true
  min_valid_positions: 5
scoring:
  default_low_score: -10.0
  normalization_method: z_score
export:
  default_format: json
  include_metadata: true
  include_conservation_profiles: true
  include_background_frequencies: true
  file_naming:
    include_cluster_id: true
    include_timestamp: false
    prefix: pssm_matrix
analysis:
  calculate_statistics: true
  identify_conserved_positions: true
  conserved_position_threshold: 0.8
  quality_metrics:
    score_distribution: true
    position_entropy: true
    matrix_completeness: true
performance:
  parallel_matrix_generation: false
  memory_efficient_mode: true
error_handling:
  skip_low_quality_alignments: true
  continue_on_matrix_failure: true
  log_failed_matrices: true
logging:
  log_level: INFO
  log_generation_progress: true
  log_quality_assessment: true
  log_matrix_statistics: true
  detailed_error_logging: true
_metadata:
  last_updated: '2025-06-22T23:41:37.559179'
  updated_by: modular_config_migration
  migration_version: 1.0.0
  uses_modular_config: true
