name: RealAlphavirusWorkflow
description: Complete real Alphavirus protein analysis workflow with PSSM generation
version: 2.0.0
execution_strategy: sequential
error_handling: stop
enable_monitoring: true
workflow_directory: nanobrain/library/workflows/viral_protein_analysis
enable_progress_reporting: true
progress_batch_interval: 5.0
progress_collapsed_by_default: false
progress_show_technical_errors: true
progress_preserve_session_history: true
max_parallel_steps: 1
timeout_seconds: 3600
steps:
- step_id: data_acquisition
  name: BV-BRC Data Acquisition
  description: Download genomes, filter by size, extract proteins, get sequences and
    annotations
  class: BVBRCDataAcquisitionStep
  logical_steps:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  config:
    bvbrc_config:
      installation_path: /Applications/BV-BRC.app/deployment
      executable_path: /Applications/BV-BRC.app/deployment/bin
      genome_batch: 100
      md5_batch: 50
      min_length: 8000
      max_length: 15000
      timeout_seconds: 300
      retry_attempts: 3
      verify_on_init: true
    min_genome_length: 8000
    max_genome_length: 15000
    genome_batch_size: 100
    md5_batch_size: 50
- step_id: annotation_mapping
  name: Annotation Mapping
  description: Handle annotation inconsistencies using ICTV mapping
  class: AnnotationMappingStep
  logical_steps:
  - 8
  depends_on:
  - data_acquisition
  config:
    annotation_config:
      use_ictv_mapping: true
      standardize_names: true
- step_id: sequence_curation
  name: Sequence Curation
  description: Sequence curation, length analysis, and quality control
  class: SequenceCurationStep
  logical_steps:
  - 9
  - 10
  - 11
  depends_on:
  - annotation_mapping
  config:
    curation_config:
      min_length: 50
      max_length: 5000
      remove_duplicates: true
      quality_threshold: 0.8
- step_id: clustering
  name: Protein Clustering
  description: Use MMseqs2 to build protein clusters
  class: ClusteringStep
  logical_steps:
  - 12
  depends_on:
  - sequence_curation
  config:
    clustering_config:
      similarity_threshold: 0.5
      min_cluster_size: 3
      max_cluster_size: 1000
      clustering_method: mmseqs2
- step_id: alignment
  name: Multiple Sequence Alignment
  description: Align protein clusters using MUSCLE
  class: AlignmentStep
  logical_steps:
  - 13
  depends_on:
  - clustering
  config_file: config/steps/alignment.yml
- step_id: pssm_analysis
  name: PSSM Analysis
  description: Generate PSSM matrices and create viral_pssm.json output
  class: PSSMAnalysisStep
  logical_steps:
  - 14
  depends_on:
  - alignment
  config:
    pssm_config:
      alphabet: protein
      method: frequency_based
      pseudocount: 0.01
      conservation_threshold: 0.7
links:
- link_id: data_to_annotation
  link_type: direct
  source: data_acquisition
  target: annotation_mapping
- link_id: annotation_to_curation
  link_type: direct
  source: annotation_mapping
  target: sequence_curation
- link_id: curation_to_clustering
  link_type: direct
  source: sequence_curation
  target: clustering
- link_id: clustering_to_alignment
  link_type: direct
  source: clustering
  target: alignment
- link_id: alignment_to_pssm
  link_type: direct
  source: alignment
  target: pssm_analysis
input_params:
  target_genus: Alphavirus
  organism: Alphavirus
output_format:
  format: json
  include_intermediate_results: true
  compress_large_data: false
resource_limits:
  max_memory_mb: 4096
  max_cpu_cores: 4
  max_disk_space_mb: 2048
error_handling_config:
  retry_failed_steps: true
  max_retries: 2
  continue_on_non_critical_errors: false
logging:
  level: INFO
  include_performance_metrics: true
  log_step_inputs_outputs: true
_metadata:
  last_updated: '2025-06-22T23:41:37.603688'
  updated_by: modular_config_migration
  migration_version: 1.0.0
  uses_modular_config: true
