name: "StepFileWriter"
description: "Step for performing file operations based on natural language descriptions"
class: "SimpleStep"  # This should be a step, not an agent

defaults:
  backup_enabled: true
  backup_extension: ".bak"
  create_directories: true
  model: "gpt-3.5-turbo"
  debug_mode: false

metadata:
  biological_analogy: "Fine motor control for writing"
  justification: >
    Like how fine motor control allows for precise writing movements,
    this tool allows for precise file writing operations.
  objectives:
    - Parse natural language instructions to extract file operations
    - Create new files with specified content
    - Read existing files with natural instructions
    - Intelligently determine file paths and content from text input
    - Create backups of files before modifying them

config:
  name: "StepFileWriter"
  description: "Step for file operations using specialized FileWriterAgent"
  debug_mode: false

# Agent configuration for the step
agent:
  class: "agents.FileWriterAgent"
  config:
    name: "StepFileWriter"
    description: "Specialized agent for file operations based on natural language descriptions"
    model: "gpt-3.5-turbo"
    temperature: 0.1
    system_prompt: |
      You are a specialized file writing agent for the NanoBrain framework.

      Your responsibilities:
      1. Create and write files based on natural language descriptions
      2. Handle file paths and directory creation
      3. Manage file permissions and error handling
      4. Provide clear feedback about file operations

      When handling file operations:
      - Create directories if they don't exist
      - Handle file permissions appropriately
      - Provide clear error messages
      - Confirm successful operations
      - Support various file formats (text, code, data files)

      You can handle direct file operations without LLM calls for simple tasks.

# Input data configurations
input_configs:
  instruction:
    data_type: "memory"
    name: "instruction"
    description: "Natural language instruction for file operation"
  content:
    data_type: "memory"
    name: "content"
    description: "Content to write to file (optional)"
    required: false

# Output data configuration
output_config:
  data_type: "file"
  name: "result"
  description: "Result of the file operation"

validation:
  required:
    - name
    - description
  optional:
    - debug_mode
    - backup_enabled
    - backup_extension
    - create_directories
  constraints:
    debug_mode:
      type: "boolean"
      description: "Enable debug mode for verbose logging."
    backup_enabled:
      type: "boolean"
      description: "Whether to create backups by default."
    backup_extension:
      type: "string"
      description: "Extension to use for backup files."
      pattern: "^\\.[a-zA-Z0-9]+$"
    create_directories:
      type: "boolean"
      description: "Whether to create parent directories if they don't exist."

input_schema:
  type: "object"
  properties:
    input:
      type: "string"
      description: "Natural language description of the file operation to perform"
      required: false
    operation:
      type: "string"
      description: "Operation to perform (write, read, append, modify, delete, backup)"
      enum: ["write", "read", "append", "modify", "delete", "backup"]
      required: false
    path:
      type: "string"
      description: "Path to the file to operate on"
      required: false
    content:
      type: "string"
      description: "Content to write to the file (for write, append, and modify operations)"
      required: false
    backup:
      type: "boolean"
      description: "Whether to create a backup before modifying/deleting a file"
      default: true
      required: false
    create_dirs:
      type: "boolean"
      description: "Whether to create parent directories when writing files"
      default: true
      required: false

examples:
  write_file:
    description: "Write content to a new file"
    input: "Create a file called 'hello.txt' with the content 'Hello, World!'"
    
  write_code_file:
    description: "Write code to a file"
    input: "Save this Python code to 'calculator.py': def add(a, b): return a + b"
    
  read_file:
    description: "Read a file"
    input: "Read the contents of 'config.json'"
    
  append_to_file:
    description: "Append content to an existing file"
    input: "Add 'New line of text' to the end of 'log.txt'"
    
  structured_operation:
    description: "Structured file operation"
    config:
      operation: "write"
      path: "data/output.txt"
      content: "Structured content"
      create_dirs: true
      backup: false 