name: Data Aggregation
description: Aggregate and combine processed viral protein data from multiple sources
estimated_time: 180.0
class: nanobrain.library.workflows.viral_protein_analysis.steps.data_aggregation_step.DataAggregationStep
step_type: simple
debug_mode: false
enable_logging: true

# Input data units (proper plural format)
input_data_units:
  pssm_data:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: pssm_data
    description: "PSSM matrices from PSSM analysis step"
    persistent: false

# Output data units (proper plural format)
output_data_units:
  aggregated_data:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: aggregated_data
    description: "Aggregated and combined viral protein data"
    persistent: false

# Step-level triggers
triggers:
  - trigger_id: input_data_received
    class: nanobrain.core.trigger.DataUnitChangeTrigger
    data_unit: pssm_data
    event_type: "set"
    description: "Execute data aggregation when PSSM data is received"

# Aggregation configuration
aggregation_config:
  merge_strategy: "comprehensive"
  handle_duplicates: true
  validate_consistency: true
  include_metadata: true
  # Moved output format options here
  output_format: "json"
  include_statistics: true
  include_provenance: true
  create_summary_report: true

# Processing configuration
processing_config:
  batch_size: 100
  parallel_processing: true
  max_concurrent_requests: 10
  memory_efficient: true

# Metadata
logical_steps_covered: [13]
step_description_detailed: 'Aggregate processed data from multiple analysis steps'

_metadata:
  last_updated: '2025-01-28'
  updated_by: 'config_alignment'
  migration_version: 2.0.0
  uses_modular_config: true 