name: PSSM Analysis
description: Generate position-specific scoring matrices (PSSM) from alignments
estimated_time: 180.0
class: "nanobrain.library.workflows.viral_protein_analysis.steps.pssm_analysis_step.PSSMAnalysisStep"
step_type: simple
debug_mode: true
enable_logging: true

# Input data units
input_data_units:
  pssm_input_clusters:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: pssm_input_clusters
    description: "Protein sequence clusters from clustering step"
    persistent: false

# Output data units
output_data_units:
  pssm_matrices:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: pssm_matrices
    description: "Generated PSSM matrices from sequence clusters"
    persistent: false

# Step-level triggers
triggers:
  - trigger_id: input_data_received
    class: nanobrain.core.trigger.DataUnitChangeTrigger
    data_unit: pssm_input_clusters
    event_type: "set"
    description: "Execute PSSM analysis when sequence clusters are received"

# PSSM-specific configuration
pssm_config:
  pseudocount: 0.1
  background_freq: uniform
  matrix_format: psi-blast
  normalize: true
  log_odds: true
  save_matrices: true
  save_logo: true
  export_formats:
    - json
    - csv
    - txt

logical_steps_covered:
- 14
step_description_detailed: 'This step performs PSSM generation:

  14. Generate position-specific scoring matrices from alignments '
_metadata:
  last_updated: '2025-06-22T23:41:37.618993'
  updated_by: modular_config_migration
  migration_version: 1.0.0
  uses_modular_config: true
