name: "ChatbotViralWorkflow"
description: "Intelligent chatbot integration with enhanced viral annotation backend"
version: "5.1.0"  # Compliance update version
execution_strategy: "event_driven"
error_handling: "continue"
enable_monitoring: true
workflow_directory: "nanobrain/library/workflows/chatbot_viral_integration"

# Existing configuration preserved
enable_progress_reporting: true
progress_batch_interval: 3.0
progress_collapsed_by_default: true
progress_show_technical_errors: true
progress_preserve_session_history: true
max_parallel_steps: 3
step_timeout: 120.0
retry_attempts: 2
retry_delay: 1.0
validate_graph: true
allow_cycles: false
require_connected_graph: true

# Data directory configuration (existing)
data_directory: "../../data"
cache_directory: "../../data/cache"
csv_file_path: "../../data/alphavirus_analysis/BVBRC_genome_alphavirus.csv"

# WORKFLOW-LEVEL INPUT/OUTPUT DATA UNITS (preserved)
input_data_units:
  user_query:
    class: "nanobrain.core.data_unit.DataUnitMemory"
    name: "user_query"
    description: "User query input for enhanced chatbot viral integration"
    persistent: false

output_data_units:
  chatbot_response:
    class: "nanobrain.core.data_unit.DataUnitMemory"
    name: "chatbot_response"
    description: "Complete chatbot response with enhanced viral analysis"
    persistent: false

# UPDATED: Dict-based steps format (was list-based)
steps:
  query_classification:
    class: "nanobrain.library.workflows.chatbot_viral_integration.steps.query_classification_step.QueryClassificationStep"
    config: "config/QueryClassificationStep/QueryClassificationStep.yml"
    name: "Query Classification"
    description: "Classify user queries and extract virus species using LLM agent"
    estimated_time: 2.0
  
  virus_name_resolution:
    class: "nanobrain.library.workflows.chatbot_viral_integration.steps.virus_name_resolution_step.EnhancedVirusNameResolutionStep"
    config: "config/VirusNameResolutionStep/VirusNameResolutionStep.yml"
    name: "Enhanced Virus Name Resolution"
    description: "Ultra-high-confidence virus synonym detection with multi-agent processing"
    estimated_time: 10.0
  
  viral_protein_analysis:
    class: "nanobrain.library.workflows.viral_protein_analysis.alphavirus_workflow.AlphavirusWorkflow"
    config: "../viral_protein_analysis/config/AlphavirusWorkflow.yml"
    name: "Enhanced Viral Protein Analysis Workflow"
    description: "Complete enhanced viral protein analysis workflow with ultra-precision validation"
    estimated_time: 1800.0
    timeout: 1800.0
  
  conversational_response:
    class: "nanobrain.library.workflows.chatbot_viral_integration.steps.conversational_response_step.ConversationalResponseStep"
    config: "config/ConversationalResponseStep/ConversationalResponseStep.yml"
    name: "Conversational Response"
    description: "Generate intelligent conversational responses about viruses"
    estimated_time: 5.0
  
  response_formatting:
    class: "nanobrain.library.workflows.chatbot_viral_integration.steps.response_formatting_step.ResponseFormattingStep"
    config: "config/ResponseFormattingStep/ResponseFormattingStep.yml"
    name: "Response Formatting"
    description: "Format enhanced analysis results for chatbot response"
    estimated_time: 5.0

# UPDATED: Dict-based links format (was list-based)
links:
  workflow_to_query_classification:
    source: "user_query"
    target: "query_classification.user_query"
    description: "Route user input to query classification"
  
  classification_to_enhanced_virus_resolution:
    source: "query_classification.extraction_result"
    target: "virus_name_resolution.query_input"
    condition:
      field: "routing_decision"
      operator: "equals"
      value: "virus_name_resolution"
    description: "Route classification result to enhanced virus resolution for ultra-precision analysis"
  
  enhanced_virus_resolution_to_viral_analysis:
    source: "virus_name_resolution.resolution_result"
    target: "viral_protein_analysis.virus_input"
    condition:
      field: "analysis_type"
      operator: "in"
      values: ["pssm", "protein_analysis"]
    description: "Route ultra-high-confidence synonyms to enhanced viral protein analysis"
  
  enhanced_viral_analysis_to_response_formatting:
    source: "viral_protein_analysis.analysis_results"
    target: "response_formatting.analysis_input"
    description: "Route enhanced viral analysis results to response formatting"
  
  formatted_enhanced_analysis_to_workflow:
    source: "response_formatting.formatted_response"
    target: "chatbot_response"
    description: "Route formatted enhanced analysis response to workflow output"
  
  classification_to_conversational_response:
    source: "query_classification.extraction_result"
    target: "conversational_response.query_input"
    condition:
      field: "routing_decision"
      operator: "equals"
      value: "conversational_response"
    description: "Route classification result to conversational response"
  
  conversational_to_response_formatting:
    source: "conversational_response.response_data"
    target: "response_formatting.response_input"
    description: "Route conversational response to formatting"
  
  formatted_conversational_to_workflow:
    source: "response_formatting.formatted_response"
    target: "chatbot_response"
    description: "Route formatted conversational response to workflow output"

# UPDATED: Dict-based triggers format (was list-based)
triggers:
  user_query_received:
    class: "nanobrain.core.trigger.DataUnitChangeTrigger"
    data_unit: "user_query"
    description: "Trigger when user query received"
  
  query_classification_completed:
    class: "nanobrain.core.trigger.DataUnitChangeTrigger"
    data_unit: "extracted_query_data"
    description: "Trigger when query classification completed"
  
  enhanced_virus_resolution_completed:
    class: "nanobrain.core.trigger.DataUnitChangeTrigger"
    data_unit: "resolution_output"
    description: "Trigger when enhanced virus name resolution completed"
  
  enhanced_viral_analysis_completed:
    class: "nanobrain.core.trigger.DataUnitChangeTrigger"
    data_unit: "analysis_results"
    description: "Trigger when enhanced viral protein analysis completed"

# Existing execution configuration (preserved)
execution:
  start_with: "query_classification"
  error_handling: "continue"
  parallel_execution: false
  timeout: 600.0

# Existing metadata (preserved)
workflow_metadata:
  framework_compliance: "from_config_mandatory"
  migration_status: "enhanced_ultra_precision_complete"
  integration_status: "enhanced_workflow_as_step_enabled"
  ultra_precision_support: "enabled"
  zero_contamination_guarantee: "enabled"
  last_updated: "2025-01-28"
  configuration_status: "enhanced_production_ready"
  notes: "Updated for framework compliance - Dict-based configuration format"
