name: ChatbotViralWorkflow
description: Intelligent chatbot integration with enhanced viral annotation backend
version: 5.0.0  # Updated version for enhanced ultra-precision support
execution_strategy: event_driven
error_handling: continue
enable_monitoring: true
workflow_directory: nanobrain/library/workflows/chatbot_viral_integration
enable_progress_reporting: true
progress_batch_interval: 3.0
progress_collapsed_by_default: true
progress_show_technical_errors: true
progress_preserve_session_history: true
max_parallel_steps: 3
step_timeout: 120.0
retry_attempts: 2
retry_delay: 1.0
validate_graph: true
allow_cycles: false
require_connected_graph: true

# Data directory configuration - configurable path for data storage and caching
data_directory: "../../data"  # Base data directory - can be overridden by environment or config
cache_directory: "../../data/cache"  # Cache directory for temporary files
csv_file_path: "../../data/alphavirus_analysis/BVBRC_genome_alphavirus.csv"  # Path to genome CSV data

# WORKFLOW-LEVEL INPUT/OUTPUT DATA UNITS (Only at workflow level)
input_data_units:
  user_query:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: user_query
    description: "User query input for enhanced chatbot viral integration"
    persistent: false

output_data_units:
  chatbot_response:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: chatbot_response
    description: "Complete chatbot response with enhanced viral analysis"
    persistent: false

# STEPS: External configuration file references only (enhanced execution chain)
steps:
- step_id: query_classification
  name: Query Classification
  description: Classify user queries and extract virus species using LLM agent
  class: nanobrain.library.workflows.chatbot_viral_integration.steps.query_classification_step.QueryClassificationStep
  estimated_time: 2.0
  config_file: config/steps/query_classification.yml

- step_id: virus_name_resolution
  name: Enhanced Virus Name Resolution
  description: Ultra-high-confidence virus synonym detection with multi-agent processing
  class: nanobrain.library.workflows.chatbot_viral_integration.steps.virus_name_resolution_step.EnhancedVirusNameResolutionStep
  estimated_time: 10.0
  config_file: config/steps/enhanced_virus_name_resolution.yml

- step_id: viral_protein_analysis
  name: Enhanced Viral Protein Analysis Workflow
  description: Complete enhanced viral protein analysis workflow with ultra-precision validation
  class: nanobrain.library.workflows.viral_protein_analysis.alphavirus_workflow.AlphavirusWorkflow
  estimated_time: 1800.0
  timeout: 1800.0
  config_file: ../viral_protein_analysis/config/AlphavirusWorkflow.yml

- step_id: conversational_response
  name: Conversational Response
  description: Generate intelligent conversational responses about viruses
  class: nanobrain.library.workflows.chatbot_viral_integration.steps.conversational_response_step.ConversationalResponseStep
  estimated_time: 5.0
  config_file: config/steps/conversational_response.yml

- step_id: response_formatting
  name: Response Formatting
  description: Format enhanced analysis results for chatbot response
  class: nanobrain.library.workflows.chatbot_viral_integration.steps.response_formatting_step.ResponseFormattingStep
  estimated_time: 5.0
  config_file: config/steps/response_formatting.yml

# EVENT-DRIVEN LINKS: Define complete data flow for enhanced ultra-precision workflow execution
links:
- link_id: workflow_to_query_classification
  source: user_query
  target: query_classification.user_query
  description: "Route user input to query classification"

# Enhanced Analysis Route: query → enhanced_virus_resolution → enhanced_viral_protein_analysis → response_formatting
- link_id: classification_to_enhanced_virus_resolution
  source: query_classification.extraction_result
  target: virus_name_resolution.query_input
  condition:
    field: routing_decision
    operator: equals
    value: virus_name_resolution
  description: "Route classification result to enhanced virus resolution for ultra-precision analysis"

- link_id: enhanced_virus_resolution_to_viral_analysis
  source: virus_name_resolution.resolution_result
  target: viral_protein_analysis.virus_input
  condition:
    field: analysis_type
    operator: in
    values: ["pssm", "protein_analysis"]
  description: "Route ultra-high-confidence synonyms to enhanced viral protein analysis"

- link_id: enhanced_viral_analysis_to_response_formatting
  source: viral_protein_analysis.analysis_results
  target: response_formatting.analysis_input
  description: "Route enhanced viral analysis results to response formatting"

- link_id: formatted_enhanced_analysis_to_workflow
  source: response_formatting.formatted_response
  target: chatbot_response
  description: "Route formatted enhanced analysis response to workflow output"

# Conversational Route: query → conversational_response → response_formatting
- link_id: classification_to_conversational_response
  source: query_classification.extraction_result
  target: conversational_response.query_input
  condition:
    field: routing_decision
    operator: equals
    value: conversational_response
  description: "Route classification result to conversational response"

- link_id: conversational_to_response_formatting
  source: conversational_response.response_data
  target: response_formatting.response_input
  description: "Route conversational response to formatting"

- link_id: formatted_conversational_to_workflow
  source: response_formatting.formatted_response
  target: chatbot_response
  description: "Route formatted conversational response to workflow output"

# Triggers
triggers:
- trigger_id: user_query_received
  class: nanobrain.core.trigger.DataUnitChangeTrigger
  data_unit: user_query
  description: "Trigger when user query received"
  
- trigger_id: query_classification_completed
  class: nanobrain.core.trigger.DataUnitChangeTrigger
  data_unit: extracted_query_data
  description: "Trigger when query classification completed"
  
- trigger_id: enhanced_virus_resolution_completed
  class: nanobrain.core.trigger.DataUnitChangeTrigger
  data_unit: resolution_output
  description: "Trigger when enhanced virus name resolution completed"
  
- trigger_id: enhanced_viral_analysis_completed
  class: nanobrain.core.trigger.DataUnitChangeTrigger
  data_unit: analysis_results
  description: "Trigger when enhanced viral protein analysis completed"

# Execution configuration
execution:
  start_with: query_classification
  error_handling: continue
  parallel_execution: false
  timeout: 600.0

# Workflow metadata
workflow_metadata:
  framework_compliance: "from_config_mandatory"
  migration_status: "enhanced_ultra_precision_complete"
  integration_status: "enhanced_workflow_as_step_enabled"
  ultra_precision_support: "enabled"
  zero_contamination_guarantee: "enabled"
  last_updated: "2025-01-28"
  configuration_status: "enhanced_production_ready"
  notes: "Enhanced for ultra-precision workflow execution with zero contamination tolerance and multi-agent validation"
