name: Conversational Response
description: Generate intelligent conversational responses about viruses
class: nanobrain.library.workflows.chatbot_viral_integration.steps.conversational_response_step.ConversationalResponseStep

# Framework settings
config:
  name: conversational_response
  description: Generate intelligent conversational responses about viruses
  debug_mode: false
  enable_logging: true
  log_data_transfers: true

# UPDATED: Input configuration with class field
input_configs:
  query_input:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: query_input
    description: "Query classification result for conversational response"
    persistent: false

# UPDATED: Output configuration with class field
output_config:
  class: nanobrain.core.data_unit.DataUnitMemory
  name: response_data
  description: "Generated conversational response data"
  persistent: false

# PURE CONFIG: Agent configuration via external file reference
conversational_agent:
  config_file: "nanobrain/library/agents/specialized/config/viral_conversation_agent.yml"

# STEP-LEVEL TRIGGER: Execute when query classification routes to conversational response
triggers:
  - trigger_id: input_data_received
    class: nanobrain.core.trigger.DataUnitChangeTrigger
    data_unit: query_input
    event_type: "set"
    description: "Execute step when query is routed to conversational response"
    condition:
      field: "routing_decision.next_step"
      operator: "equals"
      value: "conversational_response"

# Response templates
response_templates:
  general_info: |
    I can help you with information about viruses and viral proteins. 
    
    {response_content}
    
    Would you like me to analyze specific viral proteins or provide more detailed information?
  
  capability_explanation: |
    I can help you with:
    - Viral protein analysis and annotation
    - Protein sequence clustering and comparison
    - Viral taxonomy and classification
    - Functional analysis of viral proteins
    
    What specific aspect would you like to explore?
  
  follow_up_suggestion: |
    {response_content}
    
    Some follow-up questions you might consider:
    - {follow_up_questions}

# Literature search configuration
literature_search:
  enabled: true
  max_references: 5
  prefer_recent_papers: true
  citation_style: brief

# Response formatting
use_markdown: true
include_confidence_score: true
add_follow_up_suggestions: true
maintain_conversation_context: true
max_context_turns: 10

# Methodology and explanations
protein_annotation_explanations: true
methodology_descriptions: true
result_interpretation_help: true
