name: Virus Name Resolution
description: Resolve virus species using LLM with cache-first approach
class: VirusNameResolutionStep

# Framework settings
config:
  name: virus_name_resolution
  description: Resolve virus species using LLM with cache-first approach
  debug_mode: false
  enable_logging: true
  log_data_transfers: true

# UPDATED: Input data unit with class field
input_configs:
  query_input:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: query_input
    description: "Query classification result for virus name resolution"
    persistent: false

# UPDATED: Output data unit with class field
output_config:
  class: nanobrain.core.data_unit.DataUnitMemory
  name: resolution_output
  description: "Resolved virus species information for workflow input"
  persistent: false
  # Output format matches AlphavirusWorkflow input expectations

# PURE CONFIG: Agent configuration via external file reference
resolution_agent:
  config_file: "nanobrain/library/agents/specialized/config/virus_resolution_agent.yml"

# Cache configuration
cache_config:
  enable_caching: true
  cache_manager_class: nanobrain.library.workflows.viral_protein_analysis.virus_specific_cache_manager.VirusSpecificCacheManager
  cache_directory: "data/virus_resolution_cache"
  cache_ttl_hours: 24

# STEP-LEVEL TRIGGER: Execute when query classification output received
triggers:
  - trigger_id: input_data_received
    class: nanobrain.core.trigger.DataUnitChangeTrigger
    data_unit: query_input
    event_type: "set"
    description: "Execute step when query classification result is received" 