name: Protein Clustering Analysis
description: Cluster proteins by product names with LLM-generated summary
estimated_time: 60.0
class: ClusteringStep
step_type: simple
enable_logging: true
debug_mode: true

# Data directory configuration - configurable paths for data storage and caching
data_directory: "data"  # Base data directory
mmseqs2_cache_directory: "data/mmseqs2_cache"  # MMseqs2 cache directory
cache_directory: "data/cache"  # General cache directory

# Clustering configuration
clustering_config:
  method: product_based  # Default method
  use_canonical_names: true  # Use canonical names from synonym processing
  canonical_name_field: "canonical_product"
  fallback_field: "product"  # Fallback if canonical name not available
  
  # Product-based clustering parameters
  similarity_threshold: 0.9
  min_cluster_size: 2
  max_cluster_size: 1000
  
  # LLM summary configuration
  enable_llm_summary: true
  summary_format: "markdown"
  max_clusters_to_display: 20
  include_sequence_snippets: true
  snippet_length: 100

# Product-based clustering only - no tools needed

# UPDATED: Input configuration with class field
input_configs:
  curated_sequences:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: curated_sequences
    description: "Curated sequences from curation step"
    persistent: false

# UPDATED: Output configuration with class field
output_config:
  class: nanobrain.core.data_unit.DataUnitMemory
  name: cluster_results
  description: "Protein clustering results with LLM-generated summary"
  persistent: false

# ADDED: Generic trigger configuration for event-driven execution with data unit binding
trigger_config:
  trigger_type: data_updated
  name: input_data_received_trigger
  description: "Trigger when input data is received"
  data_units: ["curated_sequences"]  # BIND trigger to specific input data unit

logical_steps_covered: [10]
step_description_detailed: 'Final clustering step with synonym-aware processing'

_metadata:
  last_updated: '2025-01-28'
  updated_by: 'synonym_agent_integration'
  migration_version: 2.0.0
  uses_modular_config: true
  uses_canonical_names: true
  config_type: "step"
  framework_version: "1.0.0"
  compliance_level: "full"
  tool_integration: "from_config"
