name: Elasticsearch Indexing
description: Index viral protein data into Elasticsearch for search and analysis
estimated_time: 300.0
class: nanobrain.library.workflows.viral_protein_analysis.steps.elasticsearch_indexing_step.ElasticsearchIndexingStep
step_type: simple
debug_mode: false
enable_logging: true

# Elasticsearch configuration
elasticsearch_config:
  host: "localhost"
  port: 9200
  index_name: "viral_proteins"
  timeout: 30
  max_retries: 3

# Indexing configuration
indexing_config:
  batch_size: 100
  parallel_indexing: true
  max_concurrent_requests: 10
  include_sequences: true
  include_annotations: true

# Data transformation
transform_config:
  normalize_protein_names: true
  include_metadata: true
  create_searchable_fields: true

# Input data unit
input_data_unit:
  name: protein_data_input
  class: nanobrain.core.data_unit.DataUnit

# Output data unit
output_data_unit:
  name: elasticsearch_index_output
  class: nanobrain.core.data_unit.DataUnit

# Metadata
logical_steps_covered: [12]
step_description_detailed: 'Index processed viral protein data into Elasticsearch'

_metadata:
  last_updated: '2025-01-28'
  updated_by: 'config_alignment'
  migration_version: 2.0.0
  uses_modular_config: true 