name: Annotation Mapping
description: Handle annotation inconsistencies using ICTV mapping and synonym resolution
estimated_time: 60.0
class: AnnotationMappingStep
step_type: simple
debug_mode: true
enable_logging: true

# Tool configuration for synonym agent (NanoBrain pattern)
tools:
  synonym_agent:
    enabled: true
    class: nanobrain.library.agents.specialized.protein_synonym_agent.ProteinSynonymAgent
    config_file: "nanobrain/library/agents/specialized/config/ProteinSynonymAgent.yml"
    timeout: 300
    max_retries: 3

# Annotation configuration
annotation_config:
  use_ictv_mapping: true
  standardize_names: true
  validate_annotations: true
  batch_size: 100
  enable_caching: true
  cache_dir: "data/annotation_cache"
  cache_ttl: 3600  # 1 hour

# Input/output configuration
input_data_units:
  - "protein_annotations"
  - "unique_proteins"
output_data_units:
  - "standardized_annotations"

logical_steps_covered: [8]
step_description_detailed: 'This step handles annotation standardization:
  8. Map protein annotations to ICTV standards and resolve synonyms using LLM-powered agent'

_metadata:
  last_updated: '2025-01-28'
  updated_by: 'synonym_agent_integration'
  migration_version: 2.0.0
  uses_modular_config: true
  synonym_agent_integrated: true

# Step execution configuration
processing_mode: "standard"
max_concurrent_requests: 10
request_timeout: 300

# Link-based synonym resolution
enable_synonym_resolution: true
synonym_resolution_timeout: 120

# Output configuration
output_format: "enhanced"
include_statistics: true
include_schematics: true
include_confidence_scores: true

# Logging configuration
log_synonym_resolution: true
log_performance_metrics: true
