name: PSSM Analysis
description: Generate position-specific scoring matrices (PSSM) from alignments
estimated_time: 180.0
class: PSSMAnalysisStep
step_type: simple
debug_mode: true
enable_logging: true
pssm_config:
  pseudocount: 0.1
  background_freq: uniform
  matrix_format: psi-blast
  normalize: true
  log_odds: true
output_config:
  save_matrices: true
  save_logo: true
  export_formats:
  - json
  - csv
  - txt
logical_steps_covered:
- 14
step_description_detailed: 'This step performs PSSM generation:

  14. Generate position-specific scoring matrices from alignments '
_metadata:
  last_updated: '2025-06-22T23:41:37.618993'
  updated_by: modular_config_migration
  migration_version: 1.0.0
  uses_modular_config: true
