name: AlphavirusWorkflow
description: Comprehensive Alphavirus protein analysis workflow with clustering as final step
version: 4.6.0
execution_strategy: sequential
error_handling: continue
enable_monitoring: true
workflow_directory: nanobrain/library/workflows/viral_protein_analysis
enable_progress_reporting: true
progress_batch_interval: 3.0
progress_collapsed_by_default: true
progress_show_technical_errors: true
progress_preserve_session_history: true
max_parallel_steps: 2
step_timeout: 30.0
retry_attempts: 2
retry_delay: 5.0
validate_graph: true
allow_cycles: false
require_connected_graph: true

# Data directory configuration - configurable paths for data storage and caching
data_directory: "data"  # Base data directory - can be overridden by environment or config
bvbrc_cache_directory: "data/bvbrc_cache"  # BV-BRC specific cache directory
mmseqs2_cache_directory: "data/mmseqs2_cache"  # MMseqs2 cache directory
cache_directory: "data/cache"  # General cache directory
csv_file_path: "data/alphavirus_analysis/BVBRC_genome_alphavirus.csv"  # Path to genome CSV data

# Tool dependencies configuration (Phase 3 compliance)
tools:
  bv_brc_tool:
    config_file: config/tools/bv_brc_tool.yml
    description: BV-BRC data acquisition tool configured for Alphavirus analysis
    required_for_steps: [data_acquisition]
    version: "2.0.0"
    compliance_status: "from_config_compliant"
  mmseqs2_tool:
    config_file: config/tools/mmseqs2_tool.yml
    description: MMseqs2 clustering tool optimized for viral protein analysis (optional - product-based clustering is default)
    required_for_steps: []  # Optional since product-based clustering is now default
    version: "2.0.0"
    compliance_status: "from_config_compliant"

steps:
- step_id: data_acquisition
  name: BV-BRC Data Acquisition
  description: Acquire and filter alphavirus genome data from BV-BRC database
  class: nanobrain.library.workflows.viral_protein_analysis.steps.bv_brc_data_acquisition_step.BVBRCDataAcquisitionStep
  estimated_time: 1200.0
  timeout: 1200.0
  config_file: config/steps/data_acquisition_config.yml
  dependencies:
    tools: [bv_brc_tool]
- step_id: annotation_mapping
  name: Annotation Mapping
  description: Map and standardize protein annotations
  class: nanobrain.library.workflows.viral_protein_analysis.steps.annotation_mapping_step.AnnotationMappingStep
  estimated_time: 60.0
  timeout: 60.0
  config_file: config/steps/annotation_mapping_config.yml
- step_id: sequence_curation
  name: Sequence Curation
  description: Curate sequences based on quality metrics
  class: nanobrain.library.workflows.viral_protein_analysis.steps.sequence_curation_step.SequenceCurationStep
  estimated_time: 60.0
  timeout: 60.0
  config_file: config/steps/sequence_curation_config.yml
- step_id: clustering_analysis
  name: Protein Clustering Analysis
  description: Cluster proteins by product names with LLM-generated summary (final step)
  class: nanobrain.library.workflows.viral_protein_analysis.steps.clustering_step.ClusteringStep
  estimated_time: 60.0
  timeout: 60.0
  config_file: config/steps/clustering_config.yml
  dependencies:
    tools: []  # No required tools since product-based clustering is default

links:
- link_id: acquisition_to_annotation
  source: data_acquisition
  target: annotation_mapping
  link_type: direct
  data_mapping:
    protein_annotations: protein_annotations
    unique_proteins: unique_proteins
- link_id: annotation_to_curation
  source: annotation_mapping
  target: sequence_curation
  link_type: direct
  data_mapping:
    standardized_annotations: annotations
- link_id: curation_to_clustering
  source: sequence_curation
  target: clustering_analysis
  link_type: direct
  data_mapping:
    curated_sequences: sequences

data_units:
- name: GenomeData
  type: genomic_sequences
  persistence: persistent
- name: ProteinData
  type: protein_sequences
  persistence: persistent
- name: AnnotationData
  type: functional_annotations
  persistence: persistent
- name: ClusterData
  type: sequence_clusters
  persistence: persistent

# Workflow metadata
workflow_metadata:
  framework_compliance: "from_config_mandatory"
  migration_status: "phase3_complete"
  cleanup_status: "clustering_final_step_v4.6.0"
  last_updated: "2025-01-28"
  implemented_steps_only: true
  configuration_status: "production_ready"
  clustering_mode: "product_based_default"
  notes: "Clustering analysis configured as final step with product-based grouping and LLM summary generation"
