name: formatted_response
class: nanobrain.core.data_unit.DataUnitMemory
description: "Final formatted response for chatbot output"
persistent: false
enable_logging: true
config:
  max_size: 1048576  # 1MB
  ttl_seconds: 3600  # 1 hour 