name: Conversational Response
description: Generate intelligent conversational responses about viruses
class: nanobrain.library.workflows.chatbot_viral_integration.steps.conversational_response_step.ConversationalResponseStep

# Framework settings
config:
  name: conversational_response
  description: Generate intelligent conversational responses about viruses
  debug_mode: false
  enable_logging: true
  log_data_transfers: true

# UPDATED: Input configuration with class field
input_configs:
  query_input:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: query_input
    description: "Query classification result for conversational response"
    persistent: false

# UPDATED: Output configuration with class field
output_config:
  class: nanobrain.core.data_unit.DataUnitMemory
  name: final_response
  description: "Final conversational response with analysis results"
  persistent: false

# FIXED: Generic trigger configuration for event-driven execution with data unit binding
trigger_config:
  trigger_type: data_updated
  name: input_data_received_trigger
  description: "Trigger when input data is received"
  data_units: ["query_input"]  # BIND trigger to specific input data unit

# Conversational agent configuration
conversational_agent:
  class: SimpleAgent
  name: viral_conversation_agent
  model: "gpt-4"
  temperature: 0.7
  max_tokens: 1000
  timeout: 30
  description: "Agent for generating conversational responses about viruses"

# Conversation configuration
conversation_config:
  max_context_length: 4000
  context_compression: true
  maintain_history: true
  response_streaming: false
  temperature: 0.7
  max_tokens: 1000
  
# Response model configuration
response_model: enhanced_viral
max_response_length: 2000
include_references: true
knowledge_domains:
  - viral_structure
  - viral_replication
  - viral_diseases
  - viral_evolution
  - protein_function

# Response templates
response_templates:
  general_virus_info: |
    Based on your question about {virus_species}, here's what I can tell you:
    
    {virus_information}
    
    Would you like me to provide more specific information about any aspect of this virus?
    
  virus_transmission: |
    Regarding how {virus_species} spreads:
    
    {transmission_info}
    
    Is there a particular aspect of transmission you'd like to know more about?
    
  virus_symptoms: |
    The symptoms associated with {virus_species} infection include:
    
    {symptom_info}
    
    Please note that symptoms can vary between individuals. Consult a healthcare professional for medical advice.

# Knowledge base configuration
knowledge_base:
  enable_retrieval: true
  max_retrieved_docs: 5
  similarity_threshold: 0.7
  knowledge_sources:
    - cdc_viral_database
    - who_disease_outbreak_news
    - pubmed_viral_research
    - ictv_taxonomy

# Output format specification
output_format:
  response_text: "str"
  confidence: "float 0.0-1.0"
  knowledge_sources_used: "List[str]"
  follow_up_suggestions: "List[str]"
