name: example_workflow
description: A simple example workflow demonstrating the base Workflow class
debug_mode: true
execution_strategy: sequential
error_handling: continue
validate_graph: true
allow_cycles: false
require_connected_graph: true
steps:
- step_id: input_step
  class: nanobrain.core.step.Step
  config_file: config/steps/Step.yml
- step_id: processing_step
  class: nanobrain.core.step.Step
  config_file: config/steps/Step_1.yml
- step_id: output_step
  class: nanobrain.core.step.Step
  config_file: config/steps/Step_2.yml
links:
- link_id: input_to_processing
  source: input_step
  target: processing_step
  link_type: direct
- link_id: processing_to_output
  source: processing_step
  target: output_step
  link_type: direct
_metadata:
  config_extraction:
    extracted: true
    extraction_timestamp: '2025-06-22T23:24:34.922213'
    pattern: modular_configuration_v1
  last_updated: '2025-06-22T23:41:37.513052'
  updated_by: modular_config_migration
  migration_version: 1.0.0
  uses_modular_config: true
