# MCP (Model Context Protocol) Configuration
# This file configures MCP servers and client behavior for NanoBrain agents

mcp:
  # Client configuration - controls overall MCP behavior
  client:
    default_timeout: 30.0
    default_max_retries: 3
    default_retry_delay: 1.0
    connection_pool_size: 10
    enable_tool_caching: true
    tool_cache_ttl: 300  # seconds
    auto_discover_tools: true
    fail_on_server_error: false
    log_tool_calls: true

  # MCP servers configuration
  servers:
    # Example server with no authentication
    - name: "demo_server"
      url: "mock://demo.example.com/mcp"
      description: "Demo MCP server for testing"
      auth_type: "none"
      enabled: true
      timeout: 30.0
      max_retries: 3
      retry_delay: 1.0
      capabilities:
        - "tools"

    # Example server with Bearer token authentication
    - name: "authenticated_server"
      url: "https://api.example.com/mcp"
      description: "Production MCP server with authentication"
      auth_type: "bearer"
      auth_token: "${MCP_AUTH_TOKEN}"  # Environment variable
      enabled: true
      timeout: 45.0
      max_retries: 5
      retry_delay: 2.0
      capabilities:
        - "tools"
        - "resources"

    # Example server with OAuth authentication
    - name: "oauth_server"
      url: "https://oauth.example.com/mcp"
      description: "MCP server with OAuth authentication"
      auth_type: "oauth"
      oauth_config:
        client_id: "${OAUTH_CLIENT_ID}"
        client_secret: "${OAUTH_CLIENT_SECRET}"
        scope: "mcp:tools mcp:resources"
        token_url: "https://oauth.example.com/token"
      enabled: false  # Disabled by default
      timeout: 60.0
      max_retries: 3
      retry_delay: 1.5
      capabilities:
        - "tools"
        - "resources"
        - "prompts"

    # Local development server
    - name: "local_dev"
      url: "http://localhost:8080/mcp"
      description: "Local development MCP server"
      auth_type: "none"
      enabled: false  # Only enable for development
      timeout: 10.0
      max_retries: 1
      retry_delay: 0.5
      capabilities:
        - "tools" 