# MUSCLE Tool Configuration for Multiple Sequence Alignment
# Matches MUSCLEConfig class fields exactly

# Tool identification (using name field consistently)
name: muscle

# Installation configuration
installation_path: null
executable_path: null

# Alignment parameters
max_iterations: 16
diagonal_optimization: true
gap_open_penalty: -12.0
gap_extend_penalty: -1.0

# Quality parameters
min_sequences: 3
max_sequences: 1000
output_format: fasta
