name: Virus Name Resolution
description: Resolve virus species using LLM with cache
class: VirusNameResolutionStep

# LLM agent configuration
resolution_agent:
  class: SimpleSpecializedAgent
  model: "gpt-4"
  temperature: 0.1
  max_tokens: 200
  timeout: 30

# Cache configuration
cache_config:
  class: CacheManager
  cache_directory: "data/virus_resolution_cache"
  ttl: 86400  # 24 hours

# Prompt template for virus species resolution (NO hardcoded mappings)
resolution_prompt: |
  Resolve the following virus species to canonical ICTV taxonomy and BV-BRC search terms:
  
  Virus Species: "{virus_species}"
  
  Provide comprehensive resolution including:
  1. Canonical ICTV name
  2. BV-BRC database search terms
  3. Genome characteristics (size ranges)
  4. Taxonomic lineage
  
  Return JSON format:
  {{
    "canonical_name": "official ICTV name",
    "bvbrc_search_terms": ["search_term1", "search_term2"],
    "genome_characteristics": {{
      "min_length": 10000,
      "max_length": 15000
    }},
    "taxonomic_lineage": ["Viruses", "Family", "Genus"],
    "confidence": 0.0-1.0
  }}
  
  Return only the JSON response.

# Input data unit
input_data_unit:
  class: DataUnit
  description: Extracted virus species

# Output data unit
output_data_unit:
  class: DataUnit
  description: Resolved virus species information

# Trigger configuration (at step level)
triggers:
  - class: DataUnitChangeTrigger
    data_unit: input_data_unit
    description: Trigger when virus species extracted 