name: Annotation Mapping
description: Handle annotation inconsistencies using ICTV mapping
estimated_time: 60.0
class: AnnotationMappingStep
step_type: simple
debug_mode: true
enable_logging: true
annotation_config:
  use_ictv_mapping: true
  standardize_names: true
  validate_annotations: true
logical_steps_covered:
- 8
step_description_detailed: 'This step handles annotation standardization:

  8. Map protein annotations to ICTV standards '
_metadata:
  last_updated: '2025-06-22T23:41:37.624453'
  updated_by: modular_config_migration
  migration_version: 1.0.0
  uses_modular_config: true
