name: Enhanced BV-BRC Data Acquisition
description: Ultra-high-precision CSV matching with multi-stage validation pipeline
class: EnhancedBVBRCDataAcquisitionStep

# Framework settings
config:
  name: enhanced_bv_brc_data_acquisition
  description: Ultra-high-precision CSV matching with validation agents
  debug_mode: false
  enable_logging: true
  log_data_transfers: true

# Input data unit configuration - receives ultra-high-confidence synonyms
input_configs:
  synonyms_input:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: synonyms_input
    description: "Ultra-high-confidence synonyms and species validation criteria"
    persistent: false

# Output data unit configuration - validated genome data
output_config:
  class: nanobrain.core.data_unit.DataUnitFile
  name: validated_genomes
  description: "Validated genome data with zero contamination guarantee"
  persistent: true
  file_path: "data/bvbrc_cache/validated_genomes.json"

# ENHANCED: Multi-agent validation pipeline configuration
species_validation_agent:
  config_file: "nanobrain/library/agents/specialized/config/species_validation_agent.yml"

taxonomic_verification_agent:
  config_file: "nanobrain/library/agents/specialized/config/taxonomic_verification_agent.yml"

# CSV search agent (optional - for advanced pattern generation)
csv_search_agent:
  config_file: "nanobrain/library/agents/specialized/config/virus_synonym_detection_agent.yml"

# CRITICAL: Ultra-high-precision validation settings
confidence_threshold: 0.9  # Minimum confidence for accepting results
contamination_tolerance: 0.0  # Zero tolerance for contamination
ultra_precision_mode: true
enable_multi_stage_validation: true

# CSV file configuration
csv_file_path: "data/alphavirus_analysis/BVBRC_genome_alphavirus.csv"

# Multi-strategy search configuration
search_strategies:
  enable_exact_matching: true
  enable_partial_matching: true
  enable_fuzzy_matching: true
  enable_agent_pattern_matching: true
  fuzzy_match_threshold: 80
  partial_match_min_score: 0.7

# Validation pipeline prompts
species_validation_prompt: |
  Validate if this CSV genome entry corresponds to the target virus species with ultra-high precision:

  Target Species: "{target_species}"
  Candidate Genome Name: "{candidate_name}"
  CSV Row Data: {csv_data}
  Validation Criteria: {validation_criteria}

  CRITICAL REQUIREMENTS:
  1. ZERO TOLERANCE for false positives
  2. Validate species identity with >95% confidence
  3. Detect potential cross-species contamination
  4. Flag any ambiguous or uncertain matches
  5. Prioritize precision over recall

  VALIDATION FOCUS AREAS:
  - Exact species name matching
  - Synonym recognition and verification
  - Database naming convention compliance
  - Cross-species contamination detection
  - Taxonomic consistency at species level

  Return JSON format:
  {{
    "is_valid": true/false,
    "confidence": 0.0-1.0,
    "reasoning": "detailed validation explanation",
    "validation_details": {{
      "species_match_score": 0.0-1.0,
      "contamination_risk": 0.0-1.0,
      "naming_convention_score": 0.0-1.0
    }},
    "contamination_assessment": {{
      "cross_species_risk": "none|low|medium|high",
      "nomenclature_ambiguity": "none|low|medium|high"
    }},
    "metadata": {{
      "recommendation": "accept|reject|manual_review",
      "quality_flags": ["list of concerns if any"]
    }}
  }}

  DECISION RULES:
  - Accept ONLY if confidence ≥ 0.95 AND contamination_risk ≤ 0.05
  - Reject if any contamination indicators found
  - Be extremely conservative - false rejection preferred over false acceptance

taxonomic_validation_prompt: |
  Perform comprehensive taxonomic cross-validation for this genome entry:

  Candidate Genome Name: "{candidate_name}"
  CSV Row Data: {csv_data}
  Expected Taxonomic Constraints: {taxonomic_constraints}
  Validation Criteria: {validation_criteria}

  TAXONOMIC VALIDATION REQUIREMENTS:
  1. Verify taxonomic consistency at all hierarchy levels
  2. Detect cross-species contamination patterns
  3. Validate genus-family-order relationships
  4. Ensure ICTV compliance where applicable
  5. Flag taxonomic inconsistencies or anomalies

  COMPREHENSIVE VALIDATION CHECKS:
  - Species-level identity verification
  - Genus consistency validation
  - Family-level relationship verification
  - Order-level taxonomic alignment
  - Cross-contamination risk assessment

  Return JSON format:
  {{
    "is_valid": true/false,
    "confidence": 0.0-1.0,
    "reasoning": "detailed taxonomic analysis",
    "taxonomic_analysis": {{
      "species_consistency": {{"score": 0.0-1.0, "status": "consistent|inconsistent|uncertain"}},
      "genus_validation": {{"score": 0.0-1.0, "consistency": "match|mismatch|uncertain"}},
      "family_verification": {{"score": 0.0-1.0, "consistency": "match|mismatch|uncertain"}}
    }},
    "contamination_assessment": {{
      "cross_species_risk": {{"level": "none|low|medium|high|critical"}},
      "taxonomic_distance": {{"from_target": "close|moderate|distant|unrelated"}},
      "annotation_consistency": {{"database_agreement": 0.0-1.0}}
    }},
    "validation_metadata": {{
      "final_recommendation": "accept|reject|flag_for_review",
      "ictv_compliance": true/false,
      "contamination_check_passed": true/false
    }}
  }}

  VALIDATION DECISION MATRIX:
  - ACCEPT: confidence ≥ 0.95, perfect taxonomic alignment, zero contamination risk
  - REJECT: confidence < 0.85 OR contamination risk > 0.1 OR taxonomic inconsistencies
  - FLAG: confidence 0.85-0.94, minor uncertainties, requires expert review

# BV-BRC tool configuration
bv_brc_config:
  output_directory: "data/bvbrc_cache"
  max_retries: 3
  retry_delay: 2.0
  timeout: 300.0
  batch_size: 50

# Quality assurance configuration
quality_assurance:
  enable_confidence_validation: true
  enable_taxonomic_cross_validation: true
  enable_contamination_detection: true
  enable_audit_trail: true
  manual_review_threshold: 0.85
  strict_filtering_mode: true
  zero_contamination_guarantee: true

# Performance monitoring
performance_monitoring:
  track_validation_success_rate: true
  track_contamination_prevention: true
  track_confidence_distribution: true
  enable_detailed_logging: true
  log_validation_decisions: true

# Error handling
error_handling:
  validation_failure_action: "reject"  # reject|flag|manual_review
  contamination_detection_action: "reject"
  low_confidence_action: "reject"
  enable_fallback_validation: false  # No fallbacks - strict validation only

# Cache configuration
cache_config:
  enable_validation_caching: true
  cache_directory: "data/validation_cache"
  cache_ttl_hours: 24
  cache_validation_results: true

# Trigger configuration - activated when synonyms are ready
triggers:
  - trigger_id: synonyms_received
    class: nanobrain.core.trigger.DataUnitChangeTrigger
    data_unit: synonyms_input
    event_type: "set"
    description: "Execute enhanced CSV matching when ultra-high-confidence synonyms received"

# Audit and compliance
audit_compliance:
  enable_full_audit_trail: true
  track_validation_decisions: true
  log_contamination_checks: true
  maintain_validation_history: true
  compliance_reporting: true

# Advanced validation features
advanced_features:
  enable_cross_reference_validation: true
  enable_database_consistency_checks: true
  enable_nomenclature_standardization: true
  enable_evolutionary_distance_analysis: false  # Optional advanced feature
  enable_phylogenetic_validation: false  # Optional advanced feature 