name: Enhanced BV-BRC Data Acquisition
description: Ultra-precision CSV matching with multi-stage validation pipeline
class: nanobrain.library.workflows.viral_protein_analysis.steps.enhanced_bv_brc_data_acquisition_step.EnhancedBVBRCDataAcquisitionStep

# Step configuration
config:
  name: enhanced_bv_brc_data_acquisition
  description: Ultra-precision CSV matching with validation agents
  debug_mode: false
  enable_logging: true
  log_data_transfers: true

# STEP-LEVEL DATA UNITS: Step owns its data units
input_data_units:
  synonyms_input:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: synonyms_input
    description: "Ultra-high-confidence synonyms and species validation criteria from enhanced virus resolution"
    persistent: false

output_data_units:
  validated_genomes:
    class: nanobrain.core.data_unit.DataUnitFile
    name: validated_genomes
    description: "Validated genome data with zero contamination guarantee"
    persistent: true
    file_path: "data/bvbrc_cache/validated_genomes.json"

# Step-level triggers for event-driven execution
triggers:
  - trigger_id: input_data_received
    class: nanobrain.core.trigger.DataUnitChangeTrigger
    data_unit: synonyms_input
    event_type: "set"
    description: "Execute enhanced validation when ultra-high-confidence synonyms are received"

# ENHANCED: Tool configuration (external references - no hardcoding)
tools:
  species_validation_agent:
    config_file: "nanobrain/library/agents/specialized/config/species_validation_agent.yml"
  taxonomic_verification_agent:
    config_file: "nanobrain/library/agents/specialized/config/taxonomic_verification_agent.yml"
  bv_brc_tool:
    config_file: "nanobrain/library/tools/bioinformatics/config/bv_brc_tool.yml"

# CRITICAL: Ultra-high-precision validation settings
confidence_threshold: 0.9  # Minimum confidence for accepting results
species_validation_threshold: 0.9  # Species validation agent threshold
taxonomic_validation_threshold: 0.9  # Taxonomic verification agent threshold
contamination_tolerance: 0.0  # ZERO tolerance for contamination
ultra_precision_mode: true
enable_multi_stage_validation: true

# CSV file configuration
csv_file_path: "data/alphavirus_analysis/BVBRC_genome_alphavirus.csv"

# Multi-strategy search configuration
search_strategies:
  enable_exact_synonym_search: true
  enable_partial_synonym_search: true
  enable_fuzzy_taxonomic_search: true
  enable_agent_pattern_search: false  # Optional advanced pattern generation

# Search configuration
search_config:
  max_search_results: 100
  search_timeout: 300.0
  enable_progressive_search: true
  deduplicate_results: true

# Validation pipeline configuration
validation_pipeline:
  enable_species_validation: true
  enable_taxonomic_verification: true
  enable_final_contamination_check: true
  generate_audit_trail: true
  validation_timeout: 600.0

# Cache configuration
cache_config:
  enable_caching: true
  cache_directory: "data/enhanced_bvbrc_cache"
  cache_ttl_hours: 24
  virus_specific: true
  confidence_based_caching: true

# Output format configuration
output_format:
  include_verification_metadata: true
  include_validation_audit_trail: true
  include_confidence_scores: true
  include_contamination_assessment: true

# Performance configuration
performance_config:
  batch_size: 50
  max_concurrent_validations: 5
  memory_efficient_mode: true
  enable_progress_reporting: true

# Quality assurance configuration
quality_assurance:
  enable_confidence_validation: true
  enable_taxonomic_cross_validation: true
  enable_contamination_detection: true
  strict_filtering_mode: true
  zero_false_positive_tolerance: true

# Error handling configuration
error_handling:
  retry_failed_validations: true
  max_validation_retries: 3
  fallback_on_validation_failure: false  # Strict mode - no fallbacks
  log_all_rejections: true

# Monitoring configuration
monitoring:
  track_validation_metrics: true
  track_contamination_prevention: true
  track_confidence_distributions: true
  enable_detailed_logging: true
  generate_validation_reports: true 