name: Sequence Curation
description: Sequence curation, length analysis, and quality control
estimated_time: 60.0
config:
  class: SequenceCurationStep
  step_type: simple
  debug_mode: true
  enable_logging: true
  curation_config:
    min_length: 50
    max_length: 5000
    remove_duplicates: true
    quality_threshold: 0.8
    max_ambiguous_percent: 5.0
logical_steps_covered:
- 9
- 10
- 11
step_description_detailed: 'This step combines 3 logical workflow steps:

  9. Genome organization analysis

  10. Sequence length analysis

  11. Sequence curation based on quality metrics '
_metadata:
  last_updated: '2025-06-22T23:41:37.622892'
  updated_by: modular_config_migration
  migration_version: 1.0.0
  uses_modular_config: true
