name: Sequence Curation
description: Sequence curation, length analysis, and quality control
estimated_time: 60.0
class: nanobrain.library.workflows.viral_protein_analysis.steps.sequence_curation_step.SequenceCurationStep

# Framework settings
debug_mode: true
enable_logging: true

# Input data units
input_data_units:
  curation_input_annotations:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: curation_input_annotations
    description: "Standardized annotations from annotation mapping step"
    persistent: false

output_data_units:
  curated_sequences:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: curated_sequences
    description: "Curated sequences after quality control"
    persistent: false

# STEP-LEVEL TRIGGER: Execute when curation input annotations received
triggers:
  - trigger_id: input_data_received
    class: nanobrain.core.trigger.DataUnitChangeTrigger
    data_unit: curation_input_annotations
    event_type: "set"
    description: "Execute step when curation input annotations are received"

# Curation configuration
curation_config:
  min_length: 50
  max_length: 5000
  remove_duplicates: true
  quality_threshold: 0.8
  max_ambiguous_percent: 5.0

# Metadata
logical_steps_covered:
  - 9
  - 10
  - 11
step_description_detailed: 'This step combines 3 logical workflow steps: 9. Genome organization analysis, 10. Sequence length analysis, 11. Sequence curation based on quality metrics'
_metadata:
  last_updated: '2025-01-28'
  updated_by: 'event_driven_architecture_compliance'
  migration_version: 2.0.0
  uses_step_level_data_units: true
