name: "workflow_guard_default"
description: "Default workflow-level trigger guard configuration"

# ✅ FRAMEWORK COMPLIANCE: ConfigBase-compliant configuration
enabled: true
scope: "workflow"
protected_methods:
  - "execute"
auto_apply: true
enforcement_level: "strict"
debug_mode: false
log_guard_events: true
error_message_template: "{method} may only be invoked via {scope}-level trigger" 