# BV-BRC Tool Configuration for Viral Protein Analysis
# Matches BVBRCConfig class fields exactly

# Tool identification (using name field consistently)
name: bv_brc

# Local installation configuration (BV-BRC specific) 
installation_path: /Applications/BV-BRC.app
executable_path: /Applications/BV-BRC.app/deployment/bin

# Data processing configuration
genome_batch_size: 50
md5_batch_size: 25
min_genome_length: 8000
max_genome_length: 15000

# Progressive scaling configuration
progressive_scaling:
  1:
    limit: 5
    batch_size: 5
  2:
    limit: 10
    batch_size: 10
  3:
    limit: 20
    batch_size: 15
  4:
    limit: 50
    batch_size: 25

# Tool-specific settings
timeout_seconds: 400
verify_on_init: false
use_cache: true
retry_attempts: 2
