name: AlphavirusWorkflow
description: Comprehensive viral protein analysis workflow with clustering as final step
version: 4.7.0
execution_strategy: sequential
error_handling: continue
enable_monitoring: true
workflow_directory: nanobrain/library/workflows/viral_protein_analysis
enable_progress_reporting: true
progress_batch_interval: 3.0
progress_collapsed_by_default: true
progress_show_technical_errors: true
progress_preserve_session_history: true
max_parallel_steps: 2
step_timeout: 30.0
retry_attempts: 2
retry_delay: 5.0
validate_graph: true
allow_cycles: false
require_connected_graph: true

# Data directory configuration - configurable paths for data storage and caching
data_directory: "data"  # Base data directory - can be overridden by environment or config
bvbrc_cache_directory: "data/bvbrc_cache"  # BV-BRC specific cache directory
mmseqs2_cache_directory: "data/mmseqs2_cache"  # MMseqs2 cache directory
cache_directory: "data/cache"  # General cache directory
csv_file_path: "data/viral_analysis/BVBRC_genome_viral.csv"  # Path to genome CSV data

# REMOVED: Tool dependencies at workflow level
# Tools are now configured at step level

steps:
- step_id: data_acquisition
  name: BV-BRC Data Acquisition
  description: Acquire and filter viral genome data from BV-BRC database
  class: nanobrain.library.workflows.viral_protein_analysis.steps.data_acquisition_step.BVBRCDataAcquisitionStep
  estimated_time: 1200.0
  timeout: 1200.0
  config_file: config/steps/data_acquisition_config.yml
  # Tools configured in step config file
- step_id: annotation_mapping
  name: Annotation Mapping
  description: Map and standardize protein annotations
  class: nanobrain.library.workflows.viral_protein_analysis.steps.annotation_mapping_step.AnnotationMappingStep
  estimated_time: 60.0
  timeout: 60.0
  config_file: config/steps/annotation_mapping_config.yml
- step_id: sequence_curation
  name: Sequence Curation
  description: Curate sequences based on quality metrics
  class: nanobrain.library.workflows.viral_protein_analysis.steps.sequence_curation_step.SequenceCurationStep
  estimated_time: 60.0
  timeout: 60.0
  config_file: config/steps/sequence_curation_config.yml
- step_id: clustering_analysis
  name: Protein Clustering Analysis
  description: Cluster proteins by product names with LLM-generated summary (final step)
  class: nanobrain.library.workflows.viral_protein_analysis.steps.clustering_step.ClusteringStep
  estimated_time: 60.0
  timeout: 60.0
  config_file: config/steps/clustering_config.yml
  # Tools configured in step config file if needed

# UPDATED: Links with dot notation (backward compatible)
links:
- link_id: acquisition_to_annotation
  source: data_acquisition.fasta_and_annotations
  target: annotation_mapping.fasta_and_annotations
  
- link_id: annotation_to_curation
  source: annotation_mapping.standardized_annotations
  target: sequence_curation.standardized_annotations
  
- link_id: curation_to_clustering
  source: sequence_curation.curated_sequences
  target: clustering_analysis.curated_sequences

# UPDATED: Data units use class field
data_units:
- name: GenomeData
  class: nanobrain.core.data_unit.DataUnit
  description: "Genomic sequences data"
  persistent: true
- name: ProteinData
  class: nanobrain.core.data_unit.DataUnit
  description: "Protein sequences data"
  persistent: true
- name: AnnotationData
  class: nanobrain.core.data_unit.DataUnit
  description: "Functional annotations data"
  persistent: true
- name: ClusterData
  class: nanobrain.core.data_unit.DataUnit
  description: "Sequence clusters data"
  persistent: true

# ADDED: Input/output data units for workflow-as-step usage (Phase 3 prep)
input_data_units:
  virus_input:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: virus_input
    description: "Input data for viral protein analysis"
    persistent: false

output_data_units:
  analysis_results:
    class: nanobrain.core.data_unit.DataUnitFile
    name: analysis_results
    description: "Complete viral protein analysis results"
    persistent: true
    file_path: "results/viral_protein_analysis.json"

# Workflow metadata
workflow_metadata:
  framework_compliance: "from_config_mandatory"
  migration_status: "phase2_complete"
  last_updated: "2025-01-28"
  configuration_status: "production_ready"
  notes: "Updated for generic viral species support with class-based data units"
