name: "result_collection"
type: "result_management"
description: "Collects and organizes workflow output files"

config:
  # Output directory configuration
  output_config:
    base_directory: "data/alphavirus_analysis"
    timestamp_subdirectory: true
    generate_manifest: true
    
    # File naming configuration
    file_naming:
      prefix: "alphavirus_"
      include_timestamp: false
      
    # Archive configuration (optional)
    archive:
      enabled: false
      format: "zip"
      compress_level: 6
  
  # File type configurations
  file_types:
    filtered_genomes:
      filename: "alphavirus_filtered_genomes.json"
      format: "json"
      description: "Filtered genome data meeting size criteria"
      
    unique_proteins:
      filename: "alphavirus_unique_proteins.fasta"
      format: "fasta"
      description: "Unique protein sequences in FASTA format"
      
    protein_annotations:
      filename: "alphavirus_protein_annotations.json"
      format: "json"
      description: "Protein annotation data"
      
    clusters:
      filename: "alphavirus_clusters.json"
      format: "json"
      description: "Protein clustering results"
      
    alignments:
      filename: "alphavirus_alignments.json"
      format: "json"
      description: "Multiple sequence alignment results"
      
    pssm_matrices:
      filename: "alphavirus_pssm_matrices.json"
      format: "json"
      description: "Position-specific scoring matrices"
      
    viral_pssm_json:
      filename: "viral_pssm.json"
      format: "json"
      description: "Final viral PSSM analysis results"
      
    curation_report:
      filename: "alphavirus_curation_report.json"
      format: "json"
      description: "Quality curation report"
      
    quality_metrics:
      filename: "alphavirus_quality_metrics.json"
      format: "json"
      description: "Overall quality metrics"
  
  # File validation settings
  validation:
    check_file_sizes: true
    minimum_file_size: 10  # bytes
    validate_json_format: true
    validate_fasta_format: true

# Step execution parameters
execution:
  timeout_seconds: 120
  retry_attempts: 1 