name: Conversational Response
description: Generate intelligent conversational responses about viruses
class: nanobrain.library.workflows.chatbot_viral_integration.steps.conversational_response_step.ConversationalResponseStep

# Framework settings
config:
  name: conversational_response
  description: Generate intelligent conversational responses about viruses
  debug_mode: false
  enable_logging: true
  log_data_transfers: true

# UPDATED: Input configuration with class field
input_configs:
  query_input:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: query_input
    description: "Query classification result for conversational response"
    persistent: false

# UPDATED: Output configuration with class field
output_config:
  class: nanobrain.core.data_unit.DataUnitMemory
  name: response_data
  description: "Generated conversational response data"
  persistent: false

# Conversational agent configuration
conversational_agent:
  class: SimpleAgent
  name: viral_conversation_agent
  model: "gpt-4"
  temperature: 0.7
  max_tokens: 1000
  timeout: 30
  description: "Agent for generating conversational responses about viruses"

# Conversation configuration
conversation_config:
  max_context_length: 4000
  context_compression: true
  maintain_history: true
  response_streaming: false
  temperature: 0.7
  max_tokens: 1000
  
# Response model configuration
response_model: enhanced_viral
max_response_length: 2000
include_references: true
knowledge_domains:
  - viral_structure
  - viral_replication
  - viral_diseases
  - viral_evolution
  - protein_function

# Response templates
response_templates:
  general_info: |
    I can help you with information about viruses and viral proteins. 
    
    {response_content}
    
    Would you like me to analyze specific viral proteins or provide more detailed information?
  
  capability_explanation: |
    I can help you with:
    - Viral protein analysis and annotation
    - Protein sequence clustering and comparison
    - Viral taxonomy and classification
    - Functional analysis of viral proteins
    
    What specific aspect would you like to explore?
  
  follow_up_suggestion: |
    {response_content}
    
    Some follow-up questions you might consider:
    - {follow_up_questions}

# Literature search configuration
literature_search:
  enabled: true
  max_references: 5
  prefer_recent_papers: true
  citation_style: brief

# Response formatting
use_markdown: true
include_confidence_score: true
add_follow_up_suggestions: true
maintain_conversation_context: true
max_context_turns: 10

# Methodology and explanations
protein_annotation_explanations: true
methodology_descriptions: true
result_interpretation_help: true
