name: Query Classification
description: Extract virus species using LLM agent (NO hardcoded patterns)
class: QueryClassificationStep

# Step configuration
config:
  name: query_classification
  description: Extract virus species using LLM agent
  debug_mode: false
  enable_logging: true
  log_data_transfers: true

# Input data unit configuration
input_configs:
  user_query:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: user_query_input
    description: User query input for virus species extraction
    persistent: false

# Output data unit configuration  
output_config:
  class: nanobrain.core.data_unit.DataUnitMemory
  name: extraction_result
  description: Virus species extraction result with routing decision
  persistent: false

# Trigger configuration - activated when user query received
trigger_config:
  trigger_type: data_updated
  name: query_input_trigger
  description: Trigger processing when user query received
  data_unit: user_query

# LLM agent configuration - using mandatory from_config pattern
extraction_agent:
  class: SimpleAgent
  name: virus_extraction_agent
  model: "gpt-4"
  temperature: 0.1
  max_tokens: 100
  timeout: 30
  description: "Agent for extracting virus species from user queries"
  
# Prompt template for virus species extraction (NO hardcoded patterns)
virus_extraction_prompt: |
  Analyze the following user query and extract any virus species mentioned:
  
  Query: "{user_query}"
  
  Extract virus species names if present. Return JSON format:
  {{
    "virus_species": "exact virus species name or null if none found",
    "confidence": 0.0-1.0,
    "reasoning": "brief explanation"
  }}
  
  Examples of virus species: Chikungunya virus, Eastern equine encephalitis virus, Zika virus
  
  Return only the JSON response.
