name: Virus Name Resolution
description: Resolve virus species using LLM with cache-first approach
class: VirusNameResolutionStep

# Framework settings
config:
  name: virus_name_resolution
  description: Resolve virus species using LLM with cache-first approach
  debug_mode: false
  enable_logging: true
  log_data_transfers: true

# UPDATED: Input data unit with class field
input_configs:
  query_input:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: query_input
    description: "Query classification result for virus name resolution"
    persistent: false

# UPDATED: Output data unit with class field
output_config:
  class: nanobrain.core.data_unit.DataUnitMemory
  name: resolution_output
  description: "Resolved virus species information for workflow input"
  persistent: false
  # Output format matches AlphavirusWorkflow input expectations

# Resolution configuration
resolution_agent:
  class: SimpleAgent
  name: virus_resolution_agent
  model: "gpt-4"
  temperature: 0.1
  max_tokens: 200
  timeout: 30
  description: "Agent for resolving virus species names"

# Cache configuration
cache_config:
  enable_caching: true
  cache_manager_class: nanobrain.library.workflows.viral_protein_analysis.virus_specific_cache_manager.VirusSpecificCacheManager
  cache_directory: "data/virus_resolution_cache"
  cache_ttl_hours: 24

# Prompt template for virus species resolution (NO hardcoded mappings)
resolution_prompt: |
  Resolve the following virus species to its canonical ICTV taxonomy name:
  
  Virus: "{virus_species}"
  
  Return JSON format:
  {{
    "resolved_species": "canonical ICTV species name",
    "confidence": 0.0-1.0,
    "taxonomy_info": {{
      "genus": "genus name",
      "family": "family name"
    }},
    "synonyms": ["list of known synonyms"]
  }}
  
  Return only the JSON response. 