name: "Enhanced BV-BRC Data Acquisition Step"
description: "Ultra-precision CSV matching with multi-stage validation pipeline - Complete Configuration"
class: nanobrain.library.workflows.viral_protein_analysis.steps.enhanced_bv_brc_data_acquisition_step.EnhancedBVBRCDataAcquisitionStep

# Metadata (documentation only)
_metadata:
  workflow: "viral_protein_analysis"
  component_type: "bioinformatics_step"
  last_updated: "2025-01-28"
  configuration_completeness: "complete_for_component"

# Complete step configuration
config:
  name: enhanced_bv_brc_data_acquisition
  description: Ultra-precision CSV matching with validation agents
  debug_mode: false
  enable_logging: true
  log_data_transfers: true

# Workflow directory for resolving relative config paths
workflow_directory: "nanobrain/library/workflows/viral_protein_analysis"

# Complete step-level data units
input_data_units:
  synonyms_input:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: synonyms_input
    description: "Ultra-high-confidence synonyms and species validation criteria from enhanced virus resolution"
    persistent: false

output_data_units:
  validated_genomes:
    class: nanobrain.core.data_unit.DataUnitFile
    name: validated_genomes
    description: "Validated genome data with zero contamination guarantee"
    persistent: true
    file_path: "data/bvbrc_cache/validated_genomes.json"

# Complete step-level triggers
triggers:
  - trigger_id: input_data_received
    class: nanobrain.core.trigger.DataUnitChangeTrigger
    data_unit: synonyms_input
    event_type: "set"
    description: "Execute enhanced validation when ultra-high-confidence synonyms are received"

# Component references (complete configs in separate files)
tools:
  species_validation_agent:
    config_file: "config/DataAcquisitionStep/SynonymDetectionAgent.yml"
  taxonomic_verification_agent:
    config_file: "config/DataAcquisitionStep/TaxonomicVerificationAgent.yml"
  bv_brc_tool:
    config_file: "config/DataAcquisitionStep/BVBRCTool.yml"

# Complete step-specific configuration
confidence_threshold: 0.9
species_validation_threshold: 0.9
taxonomic_validation_threshold: 0.9
contamination_tolerance: 0.0
ultra_precision_mode: true
enable_multi_stage_validation: true

# Complete CSV file configuration
csv_file_path: "data/alphavirus_analysis/BVBRC_genome_alphavirus.csv"

# Complete multi-strategy search configuration
search_strategies:
  enable_exact_synonym_search: true
  enable_partial_synonym_search: true
  enable_fuzzy_taxonomic_search: true
  enable_agent_pattern_search: false

# Complete search configuration
search_config:
  max_search_results: 100
  search_timeout: 300.0
  enable_progressive_search: true
  deduplicate_results: true

# Complete validation pipeline configuration
validation_pipeline:
  enable_species_validation: true
  enable_taxonomic_verification: true
  enable_final_contamination_check: true
  generate_audit_trail: true
  validation_timeout: 600.0

# Complete cache configuration
cache_config:
  enable_caching: true
  cache_directory: "data/enhanced_bvbrc_cache"
  cache_ttl_hours: 24
  virus_specific: true
  confidence_based_caching: true

# Complete output format configuration
output_format:
  include_verification_metadata: true
  include_validation_audit_trail: true
  include_confidence_scores: true
  include_contamination_assessment: true

# Complete performance configuration
performance_config:
  batch_size: 50
  max_concurrent_validations: 5
  memory_efficient_mode: true
  enable_progress_reporting: true

# Complete quality assurance configuration
quality_assurance:
  enable_confidence_validation: true
  enable_taxonomic_cross_validation: true
  enable_contamination_detection: true
  strict_filtering_mode: true
  zero_false_positive_tolerance: true

# Complete error handling configuration
error_handling:
  retry_failed_validations: true
  max_validation_retries: 3
  fallback_on_validation_failure: false
  log_all_rejections: true

# Complete monitoring configuration
monitoring:
  track_validation_metrics: true
  track_contamination_prevention: true
  track_confidence_distributions: true
  enable_detailed_logging: true
  generate_validation_reports: true 