name: Annotation Mapping
description: Handle annotation inconsistencies using ICTV mapping and synonym resolution
estimated_time: 60.0
class: nanobrain.library.workflows.viral_protein_analysis.steps.annotation_mapping_step.AnnotationMappingStep
step_type: simple
debug_mode: true
enable_logging: true

# STANDARDIZED CONFIG: Agent configuration via local standardized file reference
agents:
  synonym_detection_agent:
    enabled: true
    config_file: "config/AnnotationMappingStep/SynonymDetectionAgent.yml"

# STEP-LEVEL DATA UNITS: Step owns its data units
input_data_units:
  fasta_and_annotations:
    class: nanobrain.core.data_unit.DataUnitFile
    name: fasta_and_annotations
    description: "FASTA file with protein annotations from data acquisition"
    persistent: true
    file_path: "data/bvbrc_cache/fasta_and_annotations.fasta"

output_data_units:
  standardized_annotations:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: standardized_annotations
    description: "Standardized protein annotations with ICTV mapping"
    persistent: false

# STEP-LEVEL TRIGGER: Execute when FASTA data received
triggers:
  - trigger_id: input_data_received
    class: nanobrain.core.trigger.DataUnitChangeTrigger
    data_unit: fasta_and_annotations
    event_type: "set"
    description: "Execute step when FASTA annotation data is received"

# Cache configuration (virus-specific)
cache_config:
  cache_directory: "data/virus_annotation_cache"
  cache_first: true
  cache_ttl_days: 30
  virus_specific: true

# Annotation configuration
annotation_config:
  use_ictv_mapping: true
  standardize_names: true
  validate_annotations: true
  batch_size: 100
  enable_caching: true

# Tool card format specification (corrected data flow format)
input_format:
  virus_species: str
  annotated_fasta: str
  protein_annotations: "List[Dict[str, Any]]"
  unique_proteins: "List[Dict[str, Any]]"
  protein_sequences: "List[Dict[str, Any]]"
  filtered_genomes: "List[Dict[str, Any]]"
  unique_protein_products: "List[str]"

output_format:
  # Pass-through data
  virus_species: str
  annotated_fasta: str                  # ENTIRE FASTA content
  protein_sequences: "List[Dict[str, Any]]"
  filtered_genomes: "List[Dict[str, Any]]"
  # Enhanced data
  protein_annotations: "List[Dict[str, Any]]"  # With canonical_product
  unique_proteins: "List[Dict[str, Any]]"      # With canonical_product
  unique_protein_products: "List[str]"         # REDUCED after synonym resolution
  # Downstream compatibility
  standardized_annotations: "List[Dict[str, Any]]"
  mapped_proteins: "Dict[str, List[Dict[str, Any]]]"
  synonym_groups: "Dict[str, List[Tuple[str, float]]]"

logical_steps_covered: [8]
step_description_detailed: 'This step handles annotation standardization:
  8. Map protein annotations to ICTV standards and resolve synonyms using LLM-powered agent'

_metadata:
  last_updated: '2025-01-28'
  updated_by: 'synonym_agent_integration'
  migration_version: 2.0.0
  uses_modular_config: true
  synonym_agent_integrated: true

# Step execution configuration
processing_mode: "standard"
max_concurrent_requests: 10
request_timeout: 300

# Link-based synonym resolution
enable_synonym_resolution: true
synonym_resolution_timeout: 120

# Output configuration
output_format: "enhanced"
include_statistics: true
include_schematics: true
include_confidence_scores: true

# Logging configuration
log_synonym_resolution: true
log_performance_metrics: true
