name: ConversationHistoryUnit
description: Conversation history storage with Parsl execution metadata
class: ConversationHistoryUnit
config:
  name: conversation_history
  description: Persistent conversation history with Parsl metadata tracking
  class: nanobrain.core.data_unit.DataUnitMemory
  database:
    db_path: parsl_chat_workflow_history.db
    table_name: conversations
    auto_create: true
  storage:
    max_messages_per_conversation: 1000
    auto_cleanup: true
    cleanup_days: 30
    enable_compression: false
  parsl_metadata:
    track_execution_time: true
    track_agent_distribution: true
    track_resource_usage: true
    track_performance_metrics: true
  performance:
    enable_indexing: true
    batch_size: 100
    cache_recent_messages: 50
  backup:
    enable_backup: false
    backup_interval_hours: 24
    backup_retention_days: 7
_metadata:
  last_updated: '2025-06-22T23:41:37.548433'
  updated_by: modular_config_migration
  migration_version: 1.0.0
  uses_modular_config: true
