# Virus Extraction Agent Configuration
# ✅ FRAMEWORK COMPLIANCE: Standalone agent configuration for virus species extraction
# ✅ NO DEPRECATED DEPENDENCIES: Clean configuration without chatbot_viral_integration references
# ✅ STANDARDIZED PATHS: Centralized agent configuration location

# Agent identification and metadata
agent_id: "virus_extraction_agent"
agent_name: "Virus Species Extraction Agent"
agent_description: "Specialized LLM agent for extracting virus species from natural language queries"
agent_version: "1.2.0"

# Core agent configuration
agent_type: "specialized_analysis"
base_class: "nanobrain.library.agents.specialized.query_analysis_agent.QueryAnalysisAgent"

# LLM and processing configuration
llm_config:
  model_name: "gpt-3.5-turbo"
  temperature: 0.1
  max_tokens: 500
  response_format: "json"
  
# Agent-specific behavior configuration
specialization_config:
  analysis_domain: "virology"
  extraction_focus: "virus_species_identification"
  confidence_reporting: true
  
  # Virus detection parameters
  virus_detection:
    enable_scientific_names: true
    enable_common_names: true
    enable_abbreviations: true
    confidence_threshold: 0.3
    
  # Output format specification
  output_format:
    format_type: "structured_json"
    required_fields: ["virus_names", "confidence", "analysis_type", "reasoning"]
    include_metadata: true

# Specialized prompts and instructions
prompt_templates:
  system_prompt: |
    You are a specialized virus species extraction agent. Your role is to analyze user queries 
    and identify any virus species mentioned, including scientific names, common names, and abbreviations.
    
    Key responsibilities:
    1. Extract all virus species mentioned in the query
    2. Determine the type of analysis requested (protein, sequence, PSSM, structure, conversational)
    3. Assess confidence in virus detection
    4. Provide reasoning for your analysis
    
    Always respond in valid JSON format with the required fields.
    
  extraction_prompt: |
    Analyze the following query for virus species and analysis type:
    
    Query: {user_query}
    
    Identify:
    1. Virus species (scientific names, common names, abbreviations)
    2. Analysis type (protein/sequence/pssm/structure/conversational/general)
    3. Confidence level (0.0 to 1.0)
    4. Reasoning for your analysis
    
    Respond in JSON format:
    {{
        "virus_names": ["list of detected virus species"],
        "analysis_type": "detected analysis type",
        "confidence": 0.0,
        "reasoning": "explanation of analysis"
    }}

# Agent capabilities and tools
capabilities:
  - "virus_species_extraction"
  - "scientific_name_recognition"
  - "common_name_mapping"
  - "abbreviation_expansion"
  - "analysis_type_classification"
  - "confidence_assessment"

# Performance and optimization settings
performance_config:
  enable_caching: true
  cache_ttl_seconds: 3600
  enable_parallel_processing: false
  timeout_seconds: 15
  retry_attempts: 2

# Validation and quality control
validation_config:
  enable_response_validation: true
  require_json_format: true
  validate_confidence_range: true
  minimum_reasoning_length: 10
  
# Error handling and fallback behavior
error_handling:
  enable_graceful_degradation: true
  fallback_confidence: 0.0
  fallback_analysis_type: "conversational"
  log_parsing_errors: true
  
# Integration and compatibility
framework_integration:
  component_type: "specialized_agent"
  required_interfaces: ["query_analysis", "json_output"]
  optional_interfaces: ["caching", "monitoring"]
  
# Logging and debugging
logging_config:
  log_level: "INFO"
  log_requests: true
  log_responses: false  # Set to true for debugging
  log_performance_metrics: true
  enable_detailed_tracing: false

# Virus species knowledge base (can be extended)
virus_knowledge:
  virus_families:
    - "Togaviridae"
    - "Flaviviridae" 
    - "Picornaviridae"
    - "Coronaviridae"
    - "Orthomyxoviridae"
    
  common_abbreviations:
    CHIKV: "Chikungunya virus"
    EEEV: "Eastern Equine Encephalitis virus"
    WEEV: "Western Equine Encephalitis virus"
    VEEV: "Venezuelan Equine Encephalitis virus"
    SINV: "Sindbis virus"
    SFV: "Semliki Forest virus"
    RRV: "Ross River virus"
    
  analysis_keywords:
    protein: ["protein", "amino acid", "sequence", "structure", "domain"]
    pssm: ["pssm", "matrix", "position", "weight", "motif"]
    sequence: ["nucleotide", "genome", "sequence", "alignment"]
    structure: ["structure", "3d", "fold", "conformation", "crystal"]
    
# Quality assurance and testing
testing_config:
  enable_self_testing: false
  test_queries:
    - "What is the protein structure of Chikungunya virus?"
    - "Analyze EEEV envelope protein"
    - "Create PSSM matrix for alphavirus"
    - "Tell me about virus diseases"
    
  expected_outputs:
    virus_detection_rate: 0.95
    json_format_compliance: 1.0
    average_confidence_threshold: 0.6 