name: "SimpleTestAgent"
description: "Simple conversational agent for testing YAML loading"
class: "SimpleAgent"

config:
  name: "test_agent"
  model: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 2000
  system_prompt: "You are a helpful AI assistant."
  
# Basic validation
validation:
  required:
    - model
    - temperature
  constraints:
    temperature:
      min: 0.0
      max: 1.0
      type: float
    max_tokens:
      min: 100
      max: 16000
      type: int 