name: Annotation Job Processing
description: Handle viral protein annotation job requests
estimated_time: 30.0
debug_mode: false
enable_logging: true
response_timeout: 30.0
classification_config:
  confidence_threshold: 0.7
  max_categories: 5
  use_embeddings: true
  model_name: sentence-transformers/all-MiniLM-L6-v2
  fallback_category: general
annotation_job_config:
  max_concurrent_jobs: 3
  job_timeout: 300.0
  enable_caching: true
  cache_duration: 1800
  result_format: json
conversation_config:
  max_context_length: 4000
  context_compression: true
  maintain_history: true
  response_streaming: false
  temperature: 0.7
  max_tokens: 1000
formatting_config:
  output_format: markdown
  include_metadata: true
  enable_syntax_highlighting: true
  wrap_code_blocks: true
  include_citations: false
llm_config:
  provider: openai
  model: gpt-3.5-turbo
  temperature: 0.7
  max_tokens: 1000
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
error_handling:
  retry_failed_requests: true
  max_retries: 3
  backoff_strategy: exponential
  fallback_response: I apologize, but I'm unable to process your request at the moment.
performance:
  enable_caching: true
  cache_ttl: 3600
  parallel_processing: false
  rate_limiting: true
  max_requests_per_minute: 60
safety_config:
  content_filtering: true
  toxicity_detection: true
  pii_detection: true
  response_validation: true
integration_config:
  enable_workflow_integration: true
  viral_analysis_endpoint: null
  database_connection: null
  external_apis: []
_metadata:
  config_type: chatbot_step
  framework_version: 1.0.0
  created_by: nanobrain_framework
  description: Default configuration for chatbot workflow steps
  source_workflow: nanobrain/library/workflows/chatbot_viral_integration/ChatbotViralWorkflow.yml
  step_id: annotation_job_processing
  created_from_inline: true
  based_on_default: nanobrain/library/config/defaults/chatbot_workflow_steps.yml
  created_date: '2025-06-22T23:41:37.486981'
backend_url: http://localhost:8001
api_endpoints:
  submit_job: /api/jobs/submit
  job_status: /api/jobs/{job_id}/status
  job_result: /api/jobs/{job_id}/result
  health_check: /api/health
max_concurrent_jobs: 3
job_timeout: 900.0
polling_interval: 5.0
max_polling_attempts: 180
sequence_extraction:
  max_sequences: 10
  min_sequence_length: 50
  max_sequence_length: 10000
  supported_formats:
  - fasta
  - raw
genome_id_extraction:
  pattern: \b[A-Z]{2}\d{6}\b
  max_ids: 5
organism_extraction:
  alphavirus_patterns:
  - chikungunya
  - sindbis
  - semliki
  - ross river
  - eastern equine
  - western equine
  - venezuelan equine
retry_on_backend_error: true
max_retries: 3
retry_delay: 5.0
report_progress_interval: 10.0
detailed_progress_tracking: true
