# UPDATED: Align with from_config pattern requirements
name: query_classification
description: Extract virus species using LLM agent (NO hardcoded patterns) 
class: nanobrain.library.workflows.chatbot_viral_integration.steps.query_classification_step.QueryClassificationStep

# Step configuration
config:
  debug_mode: false
  enable_logging: true
  log_data_transfers: true

# External agent configuration (pure config - no hardcoding)
extraction_agent:
  config_file: "nanobrain/library/agents/specialized/config/virus_extraction_agent.yml"

# Event-driven data units (step-level)
input_data_units:
  user_query:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: user_query_input
    description: User query input for virus species extraction
    persistent: false

output_data_units:
  extraction_result:
    class: nanobrain.core.data_unit.DataUnitMemory
    name: extraction_result
    description: Virus species extraction result with routing decision
    persistent: false

# Step-level triggers (event-driven execution)
triggers:
  - trigger_id: input_data_received
    class: nanobrain.core.trigger.DataUnitChangeTrigger
    data_unit: user_query
    event_type: "set"
    description: "Execute step when user query is received"

# Virus extraction prompt configuration (configurable - no hardcoding)
virus_extraction_prompt: |
  You are a virus nomenclature and bioinformatics analysis expert. Analyze this query: "{user_query}"
  
  Determine:
  1. Does it mention a specific virus species?
  2. Does it request bioinformatics analysis (PSSM, protein analysis, sequences)?
  3. What type of response is needed?
  
  Respond with JSON format:
  {{
    "virus_species": "detected virus name or null",
    "analysis_type": "pssm|protein_analysis|conversational|general",
    "confidence": 0.0-1.0,
    "routing_decision": "virus_name_resolution|conversational_response",
    "reasoning": "explanation of detection and routing decision"
  }}
  
  Examples:
  - "Create PSSM matrix for Chikungunya virus" → 
    {{"virus_species": "Chikungunya virus", "analysis_type": "pssm", "routing_decision": "virus_name_resolution", "confidence": 0.95}}
  - "Generate position-specific scoring matrix for EEEV" → 
    {{"virus_species": "Eastern equine encephalitis virus", "analysis_type": "pssm", "routing_decision": "virus_name_resolution", "confidence": 0.90}}
  - "Analyze protein sequences for Chikungunya" → 
    {{"virus_species": "Chikungunya virus", "analysis_type": "protein_analysis", "routing_decision": "virus_name_resolution", "confidence": 0.85}}
  - "Tell me about viruses" → 
    {{"virus_species": null, "analysis_type": "conversational", "routing_decision": "conversational_response", "confidence": 0.80}}
  
  Route to "virus_name_resolution" if virus species is detected AND analysis is requested.
  Route to "conversational_response" for general questions without specific analysis requests.
