name: "AnnotationMappingStep"
description: "Maps protein annotations to standardized names with synonym resolution"

# Annotation configuration
annotation_config:
  # ICTV mapping configuration
  use_ictv_mapping: true
  ictv_database_path: "data/ictv/alphavirus_proteins.json"
  
  # Synonym resolution configuration
  synonym_resolution:
    enabled: true
    wait_timeout: 120  # Maximum time to wait for synonym response (seconds)
    fallback_on_timeout: true  # Continue without synonyms if timeout
  
  # Protein classification rules
  classification_rules:
    structural_proteins:
      - "capsid"
      - "E1"
      - "E2"
      - "E3"
      - "6K"
    nonstructural_proteins:
      - "nsP1"
      - "nsP2"
      - "nsP3"
      - "nsP4"
      
# Processing configuration
processing:
  batch_size: 1000
  max_workers: 4
  
# Output configuration
output:
  include_original_annotations: true
  include_confidence_scores: true
  group_by_classification: true 