name: "data_aggregation"
type: "result_management"
description: "Aggregates and standardizes data from multiple workflow steps"

config:
  # Data mapping configuration for different steps
  data_mappings:
    data_acquisition:
      source_fields:
        - "filtered_genomes"
        - "unique_proteins"
        - "protein_sequences"
        - "protein_annotations"
        - "annotated_fasta"
        - "original_genomes"
      target_section: "genome_data"
      field_mappings: {}
    
    annotation_mapping:
      source_fields:
        - "standardized_annotations"
        - "genome_schematics"
      target_section: "analysis_data"
      field_mappings: {}
    
    sequence_curation:
      source_fields:
        - "length_analysis"
        - "curation_report"
        - "problematic_sequences"
      target_section: "quality_data"
      field_mappings: {}
    
    clustering:
      source_fields:
        - "clusters"
        - "clustering_analysis"
      target_section: "analysis_data"
      field_mappings: {}
    
    alignment:
      source_fields:
        - "aligned_clusters"
        - "alignment_quality_stats"
      target_section: "analysis_data"
      field_mappings: {}
    
    pssm_analysis:
      source_fields:
        - "pssm_matrices"
        - "final_curation_report"
        - "viral_pssm_json"
      target_section: "analysis_data"
      field_mappings: {}
  
  # Output format configuration
  output_format:
    standardize_keys: false
    include_metadata: true
  
  # Quality assurance settings
  quality_checks:
    validate_data_completeness: true
    required_sections:
      - "genome_data"
      - "analysis_data"
    minimum_completeness_score: 0.7

# Step execution parameters
execution:
  timeout_seconds: 60
  retry_attempts: 2 