# Default Configuration for Agents
# Classes:
# - nanobrain.library.agents.specialized.base.SimpleSpecializedAgent
# - nanobrain.library.agents.specialized.base.ConversationalSpecializedAgent
# - nanobrain.library.agents.enhanced.collaborative_agent.CollaborativeAgent
# - nanobrain.library.agents.conversational.enhanced_collaborative_agent.EnhancedCollaborativeAgent

# Basic agent settings
name: "DefaultAgent"
description: "Default agent configuration"
agent_type: "simple"  # simple, conversational, collaborative, enhanced

# Core agent properties
max_iterations: 100
timeout: 300.0  # 5 minutes
enable_logging: true
debug_mode: false

# LLM Configuration
llm_config:
  provider: "openai"
  model: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 1000
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0

# Memory settings
memory_config:
  enabled: true
  max_memory_size: 1000
  persistence: false
  memory_type: "simple"

# Tool configuration
tools_config:
  enabled: true
  max_tools: 10
  tool_timeout: 60.0
  allow_dangerous_tools: false

# Collaboration settings (for collaborative agents)
collaboration_config:
  enabled: false
  max_collaborators: 5
  collaboration_timeout: 120.0
  consensus_threshold: 0.6

# Conversation settings (for conversational agents)
conversation_config:
  max_context_length: 4000
  context_compression: true
  maintain_history: true
  response_streaming: false

# Specialized settings (for specialized agents)
specialization_config:
  domain: "general"
  expertise_level: "intermediate"
  specialized_tools: []
  domain_knowledge_base: null

# Performance and monitoring
performance_config:
  track_metrics: true
  cache_responses: false
  parallel_processing: false
  rate_limiting: false

# Safety and ethics
safety_config:
  content_filtering: true
  ethical_guidelines: true
  harm_prevention: true
  privacy_protection: true

# Error handling
error_handling:
  retry_failed_requests: true
  max_retries: 3
  backoff_strategy: "exponential"
  fallback_model: null

# Framework metadata
_metadata:
  config_type: "agent"
  framework_version: "1.0.0"
  created_by: "nanobrain_framework"
  description: "Default configuration for all agent types" 