# Default Configuration for Bioinformatics Tools
# Classes:
# - nanobrain.library.tools.bioinformatics.bv_brc_tool.BVBRCTool
# - nanobrain.library.tools.bioinformatics.mmseqs_tool.MMseqs2Tool
# - nanobrain.library.tools.bioinformatics.muscle_tool.MUSCLETool
# - nanobrain.library.tools.bioinformatics.pubmed_client.PubMedClient

# Basic tool settings
name: "DefaultBioinformaticsTool"
description: "Default bioinformatics tool configuration"
tool_type: "analysis"  # analysis, database, alignment, search

# Common tool settings
timeout: 600.0  # 10 minutes default for bioinformatics operations
max_retries: 3
retry_delay: 2.0
debug_mode: false
verbose: false

# BV-BRC Tool Configuration
bv_brc_config:
  base_url: "https://www.bv-brc.org/api"
  api_timeout: 300.0
  max_results: 10000
  data_format: "json"
  include_metadata: true
  cache_results: true
  cache_duration: 3600  # 1 hour

# MMseqs2 Tool Configuration
mmseqs2_config:
  executable_path: "mmseqs"
  temporary_directory: "/tmp/mmseqs2"
  sensitivity: 7.5
  coverage: 0.8
  max_target_seqs: 1000
  threads: 4
  cleanup_temp_files: true

# MUSCLE Tool Configuration
muscle_config:
  executable_path: "muscle"
  max_iterations: 16
  diagonal_optimization: true
  log_level: "info"
  output_format: "fasta"
  quiet_mode: false

# PubMed Client Configuration
pubmed_config:
  base_url: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"
  api_key: null  # Optional API key for higher rate limits
  email: null    # Required for API usage
  rate_limit: 3  # Requests per second
  max_retries: 5
  retry_backoff: 1.0

# Data handling
data_config:
  input_validation: true
  output_validation: true
  data_compression: false
  streaming: false
  batch_processing: true
  batch_size: 100

# Performance settings
performance_config:
  parallel_execution: false
  max_workers: 4
  memory_limit: "4GB"
  cpu_limit: null
  io_timeout: 120.0

# Quality control
quality_config:
  validate_sequences: true
  check_file_integrity: true
  verify_tool_availability: true
  log_tool_versions: true

# Output settings
output_config:
  save_intermediate_files: false
  compress_outputs: false
  include_metadata: true
  generate_reports: true

# Security settings
security_config:
  sanitize_inputs: true
  validate_file_paths: true
  restrict_network_access: false
  audit_trail: true

# Framework metadata
_metadata:
  config_type: "bioinformatics_tool"
  framework_version: "1.0.0"
  created_by: "nanobrain_framework"
  description: "Default configuration for bioinformatics tools" 