# Default Configuration for Viral Protein Analysis Workflow Steps
# Classes:
# - nanobrain.library.workflows.viral_protein_analysis.steps.bv_brc_data_acquisition_step.BVBRCDataAcquisitionStep
# - nanobrain.library.workflows.viral_protein_analysis.steps.sequence_curation_step.SequenceCurationStep
# - nanobrain.library.workflows.viral_protein_analysis.steps.clustering_step.ClusteringStep
# - nanobrain.library.workflows.viral_protein_analysis.steps.annotation_mapping_step.AnnotationMappingStep
# - nanobrain.library.workflows.viral_protein_analysis.steps.alignment_step.AlignmentStep
# - nanobrain.library.workflows.viral_protein_analysis.steps.pssm_analysis_step.PSSMAnalysisStep
# - nanobrain.library.workflows.viral_protein_analysis.steps.report_generation_step.ReportGenerationStep

# Basic step settings
name: "DefaultViralAnalysisStep"
description: "Default configuration for viral protein analysis workflow steps"

# Common workflow step settings
estimated_time: 300.0  # 5 minutes default
debug_mode: false
enable_logging: true
enable_progress_reporting: true

# BV-BRC Data Acquisition Settings
bvbrc_config:
  installation_path: "/Applications/BV-BRC.app/deployment"
  executable_path: "/Applications/BV-BRC.app/deployment/bin"
  api_base_url: "https://www.bv-brc.org/api"
  timeout_seconds: 300
  retry_attempts: 3
  genome_batch: 100
  md5_batch: 50
  min_length: 8000
  max_length: 15000
  verify_on_init: false

# Data acquisition parameters
target_genus: "Alphavirus"
min_genome_length: 8000
max_genome_length: 15000
genome_batch_size: 100
md5_batch_size: 50

# Sequence curation settings
curation_config:
  min_length: 50
  max_length: 5000
  remove_duplicates: true
  quality_threshold: 0.8
  max_ambiguous_percent: 5.0
  min_annotation_confidence: 0.6

# Clustering configuration
clustering_config:
  clustering_method: "mmseqs2"
  similarity_threshold: 0.7
  coverage_threshold: 0.8
  min_cluster_size: 3
  max_cluster_size: 1000
  mmseqs_config:
    sensitivity: 7.5
    cluster_mode: 0
    coverage: 0.8
    min_seq_id: 0.7

# Alignment configuration
alignment_config:
  alignment_method: "muscle"
  min_alignment_length: 100
  max_gap_percentage: 50.0
  validate_alignment_quality: true
  muscle_config:
    max_iterations: 16
    diagonal_optimization: true

# PSSM analysis configuration
pssm_config:
  create_pssm_matrices: true
  conservation_threshold: 0.8
  position_specific_scoring: true
  output_format: "json"

# Annotation mapping configuration
annotation_config:
  standardize_names: true
  use_ictv_mapping: true
  validate_annotations: true
  consensus_threshold: 0.6

# Report generation configuration
report_config:
  generate_summary: true
  include_statistics: true
  output_formats: ["html", "json", "csv"]
  include_visualizations: true

# Quality control settings
quality_control:
  validate_input_data: true
  check_sequence_integrity: true
  verify_annotations: true
  report_anomalies: true

# Performance settings
performance:
  enable_parallel_processing: false
  max_workers: 4
  memory_limit: "4GB"
  enable_caching: true
  cache_duration: 3600

# Output settings
output:
  save_intermediate_results: true
  compress_outputs: false
  include_metadata: true
  preserve_provenance: true

# Framework metadata
_metadata:
  config_type: "viral_analysis_step"
  framework_version: "1.0.0"
  created_by: "nanobrain_framework"
  description: "Default configuration for viral protein analysis workflow steps" 