web_interface:
  name: "nanobrain_web_interface"
  version: "1.0.0"
  description: "NanoBrain Web Interface for Chat Workflows"
  
  server:
    host: "0.0.0.0"
    port: 8001
    workers: 1
    reload: false
    access_log: true
    
  api:
    prefix: "/api/v1"
    title: "NanoBrain Chat API"
    description: "REST API for NanoBrain Chat System with Real-time WebSocket Support"
    version: "1.0.0"
    docs_url: "/docs"
    redoc_url: "/redoc"
    
  cors:
    allow_origins: ["*"]  # For development - restrict in production
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["*"]
    allow_credentials: false
    
  chat:
    default_temperature: 0.7
    default_max_tokens: 2000
    default_use_rag: false
    enable_streaming: true  # Enable streaming for frontend
    conversation_timeout_seconds: 3600
    max_conversation_length: 100
    
  # WebSocket configuration for real-time features
  websocket:
    enable_websocket: true
    ping_interval: 30  # seconds
    ping_timeout: 10   # seconds
    max_connections: 100
    enable_compression: true
    
  # Frontend integration settings
  frontend:
    enable_static_files: false  # Set to true if serving frontend from same server
    static_directory: "frontend/dist"
    enable_api_docs: true
    enable_error_details: true  # Detailed error responses for development
    
  logging:
    enable_request_logging: true
    enable_response_logging: true
    log_level: "INFO"
    log_requests_body: false
    log_responses_body: false
    
  security:
    enable_rate_limiting: false  # Can be enabled for production
    rate_limit_per_minute: 60
    enable_auth: false
    auth_secret_key: null
    cors_enabled: true
    
  # Integration with NanoBrain workflows
  workflow_config_path: null
  enable_workflow_metrics: true
  
  # Performance settings for frontend
  performance:
    response_timeout: 30
    max_request_size: "10MB"
    enable_gzip: true
    
  # Custom settings for extensibility
  custom_settings:
    # Environment-specific overrides
    development:
      enable_debug: true
      reload: true
      log_level: "DEBUG"
    production:
      enable_debug: false
      reload: false
      log_level: "INFO"
      cors_allow_origins: ["https://yourdomain.com"] 